## Global values for parent chart and subcharts.
global:
  spring:
    ## Use default consul address `consul-agent.local` or use pod host IP.
    useDefaultConsul: false

messaging-service:
  messaging-frontend:
    enabled: true
  messaging-backend:
    enabled: true


infrastructure:
  genericServices:
    messaging-db:
      enabled: true
      storageClassName:	nfs-delete