version: "3.6"

services:
  backend:
    build:
      context: messaging-backend
      args:
        JAR_FILE: target/messaging-backend.jar

  messaging-frontend:
    build:
      context: messaging-admin-frontend
      args:
        JAR_FILE: target/messaging-admin-frontend.jar

  react:
    build:
      context: messaging-react
      args:
        NPM_REGISTRY: https://npm.i-novus.ru