version: "3.6"
services:
  db:
    image: postgres:9.6.11-alpine
    volumes:
    - messaging-db-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432"
    deploy:
      resources:
        limits:
          memory: 1024M
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
        - node.labels.type == db

  backend:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/messaging/rest:${TAG}"
    environment:
      SPRING_APPLICATION_NAME: "messaging-backend"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_OPTS: -Xmx200m
    depends_on:
    - db
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 500M
      restart_policy:
        max_attempts: 3

  frontend:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/messaging/frontend:${TAG}"
    environment:
      SPRING_APPLICATION_NAME: "messaging-frontend"
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_OPTS: -Xmx200m
    depends_on:
    - backend
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 500M
      restart_policy:
        max_attempts: 3

  react:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/messaging/react:${TAG}"
    ports:
    - "80"
    deploy:
      resources:
        limits:
          memory: 200M
      restart_policy:
        max_attempts: 3

  security-admin-backend:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/security-admin/backend:${TAG}"
    environment:
      SPRING_APPLICATION_NAME: "messaging-security-admin-backend"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      JAVA_OPTS: -Xmx150m
    depends_on:
    - db
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 400M
      restart_policy:
        max_attempts: 3

  security-admin-frontend:
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/security-admin/frontend:${TAG}"
    environment:
      SPRING_APPLICATION_NAME: "messaging-security-admin-frontend"
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      SEC_ADMIN_REST_URL: http://security-admin-backend:8080/api
      KEYCLOAK_REALM: messaging
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_OPTS: -Xmx200m
    depends_on:
    - security-admin-backend
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 500M
      restart_policy:
        max_attempts: 3

volumes:
  messaging-db-data:
