version: "3.6"
services:
  db:
    image: postgres:9.6.11-alpine
    volumes:
    - messaging-db-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432"
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
        - node.labels.type == db

  backend:
    environment:
      SPRING_CLOUD_CONSUL_CONFIG_ENABLED: "true"
      SPRING_CLOUD_CONSUL_CONFIG_FORMAT: YAML
      SPRING_APPLICATION_NAME: "messaging-backend"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_OPTS: -Xmx200m
      SERVER_PORT: 8080
    depends_on:
    - db
    ports:
    - "8112:8080"
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3

  messaging-frontend:
    environment:
      SPRING_APPLICATION_NAME: "messaging-admin-frontend"
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SECURITY_OAUTH2_AUTH_SERVER_URI: http://yandex.develop:8278
      SECURITY_OAUTH2_CLIENT_CLIENT_ID: frontend
      SECURITY_OAUTH2_CLIENT_CLIENT_SECRET: ca12a678-b275-499b-a778-750bad4d0a77
      ACCESS_SERVICE_URL: http://yandex.develop:8278/api
      MESSAGING_BACKEND_PATH: http://backend:8080/api
      MESSAGING_USER_ADMIN_URL: http://yandex.develop:8277
      JAVA_OPTS: -Xmx200m
    depends_on:
    - backend
    ports:
    - "8111:8080"
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3

  react:
    ports:
    - "8110:80"
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3
    depends_on:
      - messaging-frontend

  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    ports:
    - '8113:2181'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.75'
      restart_policy:
        max_attempts: 3
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: 'bitnami/kafka:2.8.1'
    ports:
    - '8114:9092'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.75'
      restart_policy:
        max_attempts: 3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

volumes:
  messaging-db-data:
