version: "3.6"
services:
  db:
    image: postgres:9.6.11-alpine
    volumes:
    - messaging-db-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432"
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
        - node.labels.type == db

  backend:
    environment:
      SPRING_APPLICATION_NAME: "messaging-backend"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_OPTS: -Xmx200m
    depends_on:
    - db
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3

  messaging-frontend:
    environment:
      SPRING_APPLICATION_NAME: "messaging-admin-frontend"
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_OPTS: -Xmx200m
    depends_on:
    - backend
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3

  react:
    ports:
    - "80"
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3

volumes:
  messaging-db-data:
