version: "3.6"
services:
  db:
    image: postgres:9.6.11-alpine
    volumes:
    - messaging-db-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432"
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
        - node.labels.type == db

  backend:
    environment:
      SPRING_APPLICATION_NAME: "messaging-backend"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SEC_ADMIN_REST_URL: http://yandex.develop:8278/api
      JAVA_OPTS: -Xmx200m
      SERVER_PORT: 8080
      MESSAGING_USER_PROVIDER_URL: http://yandex.develop:8278/api/users
      MESSAGING_ROLE_PROVIDER_URL: http://yandex.develop:8278/api/role
    depends_on:
    - db
    ports:
    - "8112:8080"
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3

  messaging-frontend:
    environment:
      SPRING_APPLICATION_NAME: "messaging-admin-frontend"
      SPRING_CLOUD_CONSUL_HOST: consul-agent.local
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      SECURITY_OAUTH2_AUTH_SERVER_URI: http://yandex.develop:8278
      SECURITY_OAUTH2_CLIENT_CLIENT_ID: frontend
      SECURITY_OAUTH2_CLIENT_CLIENT_SECRET: ca12a678-b275-499b-a778-750bad4d0a77
      ACCESS_SERVICE_URL: http://yandex.develop:8278/api
      MESSAGING_BACKEND_PATH: http://backend:8080/api
      MESSAGING_USER_ADMIN_URL: http://yandex.develop:8277
      JAVA_OPTS: -Xmx200m
    depends_on:
    - backend
    ports:
    - "8111:8080"
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3

  react:
    ports:
    - "8110:80"
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '0.5'
      restart_policy:
        max_attempts: 3
    depends_on:
      - messaging-frontend

volumes:
  messaging-db-data:
