version: "3.6"

services:
  backend:
    build:
      context: messaging-rest
      args:
        JAR_FILE: target/messaging-rest.jar

  messaging-frontend:
    build:
      context: messaging-admin-frontend
      args:
        JAR_FILE: target/messaging-admin-frontend.jar
