version: "3.6"

services:
  backend:
    build:
      context: .
      args:
        JAR_FILE: messaging-rest/target/messaging-rest.jar
  frontend:
    build:
      context: .
      args:
        JAR_FILE: messaging-admin-frontend/target/messaging-admin-frontend.jar
  react:
    build:
      context: messaging-react
      args:
        NPM_REGISTRY: https://npm.i-novus.ru