/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.inovus.messaging.api.model.enums.MessageStatusType;
import ru.inovus.messaging.impl.jooq.Keys;
import ru.inovus.messaging.impl.jooq.Messaging;
import ru.inovus.messaging.impl.jooq.tables.Message.MessagePath;
import ru.inovus.messaging.impl.jooq.tables.records.MessageRecipientRecord;
import ru.inovus.messaging.impl.util.MessageStatusTypeConverter;


/**
 * Получатель уведомления
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRecipient extends TableImpl<MessageRecipientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>messaging.message_recipient</code>
     */
    public static final MessageRecipient MESSAGE_RECIPIENT = new MessageRecipient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessageRecipientRecord> getRecordType() {
        return MessageRecipientRecord.class;
    }

    /**
     * The column <code>messaging.message_recipient.id</code>. Уникальный
     * идентификатор
     */
    public final TableField<MessageRecipientRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "Уникальный идентификатор");

    /**
     * The column <code>messaging.message_recipient.message_id</code>.
     * Идентификатор уведомления
     */
    public final TableField<MessageRecipientRecord, UUID> MESSAGE_ID = createField(DSL.name("message_id"), SQLDataType.UUID, this, "Идентификатор уведомления");

    /**
     * The column <code>messaging.message_recipient.status_time</code>. Время
     * установки статуса
     */
    public final TableField<MessageRecipientRecord, LocalDateTime> STATUS_TIME = createField(DSL.name("status_time"), SQLDataType.LOCALDATETIME(6), this, "Время установки статуса");

    /**
     * The column <code>messaging.message_recipient.recipient_name</code>. Имя
     * контакта получателя
     */
    public final TableField<MessageRecipientRecord, String> RECIPIENT_NAME = createField(DSL.name("recipient_name"), SQLDataType.VARCHAR, this, "Имя контакта получателя");

    /**
     * The column <code>messaging.message_recipient.recipient_username</code>.
     * Уникальное имя пользователя из провайдера
     */
    public final TableField<MessageRecipientRecord, String> RECIPIENT_USERNAME = createField(DSL.name("recipient_username"), SQLDataType.VARCHAR, this, "Уникальное имя пользователя из провайдера");

    /**
     * The column <code>messaging.message_recipient.status</code>. Текущий
     * статус отправки уведомления получателю
     */
    public final TableField<MessageRecipientRecord, MessageStatusType> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR, this, "Текущий статус отправки уведомления получателю", new MessageStatusTypeConverter());

    /**
     * The column <code>messaging.message_recipient.departured_at</code>. Дата и
     * время фактической отправки уведомления
     */
    public final TableField<MessageRecipientRecord, LocalDateTime> DEPARTURED_AT = createField(DSL.name("departured_at"), SQLDataType.LOCALDATETIME(6), this, "Дата и время фактической отправки уведомления");

    /**
     * The column <code>messaging.message_recipient.send_message_error</code>.
     * Сообщение ошибки отправки уведомления
     */
    public final TableField<MessageRecipientRecord, String> SEND_MESSAGE_ERROR = createField(DSL.name("send_message_error"), SQLDataType.VARCHAR, this, "Сообщение ошибки отправки уведомления");

    private MessageRecipient(Name alias, Table<MessageRecipientRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MessageRecipient(Name alias, Table<MessageRecipientRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Получатель уведомления"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>messaging.message_recipient</code> table
     * reference
     */
    public MessageRecipient(String alias) {
        this(DSL.name(alias), MESSAGE_RECIPIENT);
    }

    /**
     * Create an aliased <code>messaging.message_recipient</code> table
     * reference
     */
    public MessageRecipient(Name alias) {
        this(alias, MESSAGE_RECIPIENT);
    }

    /**
     * Create a <code>messaging.message_recipient</code> table reference
     */
    public MessageRecipient() {
        this(DSL.name("message_recipient"), null);
    }

    public <O extends Record> MessageRecipient(Table<O> path, ForeignKey<O, MessageRecipientRecord> childPath, InverseForeignKey<O, MessageRecipientRecord> parentPath) {
        super(path, childPath, parentPath, MESSAGE_RECIPIENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MessageRecipientPath extends MessageRecipient implements Path<MessageRecipientRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MessageRecipientPath(Table<O> path, ForeignKey<O, MessageRecipientRecord> childPath, InverseForeignKey<O, MessageRecipientRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MessageRecipientPath(Name alias, Table<MessageRecipientRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MessageRecipientPath as(String alias) {
            return new MessageRecipientPath(DSL.name(alias), this);
        }

        @Override
        public MessageRecipientPath as(Name alias) {
            return new MessageRecipientPath(alias, this);
        }

        @Override
        public MessageRecipientPath as(Table<?> alias) {
            return new MessageRecipientPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Messaging.MESSAGING;
    }

    @Override
    public UniqueKey<MessageRecipientRecord> getPrimaryKey() {
        return Keys.MESSAGE_RECIPIENT_PKEY;
    }

    @Override
    public List<ForeignKey<MessageRecipientRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MESSAGE_RECIPIENT__MESSAGE_RECIPIENT_MESSAGE_ID_FKEY);
    }

    private transient MessagePath _message;

    /**
     * Get the implicit join path to the <code>messaging.message</code> table.
     */
    public MessagePath message() {
        if (_message == null)
            _message = new MessagePath(this, Keys.MESSAGE_RECIPIENT__MESSAGE_RECIPIENT_MESSAGE_ID_FKEY, null);

        return _message;
    }

    @Override
    public MessageRecipient as(String alias) {
        return new MessageRecipient(DSL.name(alias), this);
    }

    @Override
    public MessageRecipient as(Name alias) {
        return new MessageRecipient(alias, this);
    }

    @Override
    public MessageRecipient as(Table<?> alias) {
        return new MessageRecipient(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRecipient rename(String name) {
        return new MessageRecipient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRecipient rename(Name name) {
        return new MessageRecipient(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRecipient rename(Table<?> name) {
        return new MessageRecipient(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRecipient where(Condition condition) {
        return new MessageRecipient(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRecipient where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRecipient where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRecipient where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRecipient where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRecipient where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRecipient where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRecipient where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRecipient whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRecipient whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
