/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.inovus.messaging.impl.jooq.Indexes;
import ru.inovus.messaging.impl.jooq.Keys;
import ru.inovus.messaging.impl.jooq.Messaging;
import ru.inovus.messaging.impl.jooq.tables.RecipientGroup.RecipientGroupPath;
import ru.inovus.messaging.impl.jooq.tables.records.RecipientGroupUserRecord;


/**
 * Связь получателей с группой
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecipientGroupUser extends TableImpl<RecipientGroupUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>messaging.recipient_group_user</code>
     */
    public static final RecipientGroupUser RECIPIENT_GROUP_USER = new RecipientGroupUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecipientGroupUserRecord> getRecordType() {
        return RecipientGroupUserRecord.class;
    }

    /**
     * The column <code>messaging.recipient_group_user.id</code>. Уникальный
     * идентификатор
     */
    public final TableField<RecipientGroupUserRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "Уникальный идентификатор");

    /**
     * The column
     * <code>messaging.recipient_group_user.recipient_group_id</code>. Ссылка на
     * группу
     */
    public final TableField<RecipientGroupUserRecord, Integer> RECIPIENT_GROUP_ID = createField(DSL.name("recipient_group_id"), SQLDataType.INTEGER.nullable(false), this, "Ссылка на группу");

    /**
     * The column <code>messaging.recipient_group_user.recipient_name</code>.
     * Имя получателя
     */
    public final TableField<RecipientGroupUserRecord, String> RECIPIENT_NAME = createField(DSL.name("recipient_name"), SQLDataType.VARCHAR.nullable(false), this, "Имя получателя");

    /**
     * The column
     * <code>messaging.recipient_group_user.recipient_username</code>. ID
     * получателя
     */
    public final TableField<RecipientGroupUserRecord, String> RECIPIENT_USERNAME = createField(DSL.name("recipient_username"), SQLDataType.VARCHAR.nullable(false), this, "ID получателя");

    private RecipientGroupUser(Name alias, Table<RecipientGroupUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RecipientGroupUser(Name alias, Table<RecipientGroupUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Связь получателей с группой"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>messaging.recipient_group_user</code> table
     * reference
     */
    public RecipientGroupUser(String alias) {
        this(DSL.name(alias), RECIPIENT_GROUP_USER);
    }

    /**
     * Create an aliased <code>messaging.recipient_group_user</code> table
     * reference
     */
    public RecipientGroupUser(Name alias) {
        this(alias, RECIPIENT_GROUP_USER);
    }

    /**
     * Create a <code>messaging.recipient_group_user</code> table reference
     */
    public RecipientGroupUser() {
        this(DSL.name("recipient_group_user"), null);
    }

    public <O extends Record> RecipientGroupUser(Table<O> path, ForeignKey<O, RecipientGroupUserRecord> childPath, InverseForeignKey<O, RecipientGroupUserRecord> parentPath) {
        super(path, childPath, parentPath, RECIPIENT_GROUP_USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RecipientGroupUserPath extends RecipientGroupUser implements Path<RecipientGroupUserRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RecipientGroupUserPath(Table<O> path, ForeignKey<O, RecipientGroupUserRecord> childPath, InverseForeignKey<O, RecipientGroupUserRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RecipientGroupUserPath(Name alias, Table<RecipientGroupUserRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RecipientGroupUserPath as(String alias) {
            return new RecipientGroupUserPath(DSL.name(alias), this);
        }

        @Override
        public RecipientGroupUserPath as(Name alias) {
            return new RecipientGroupUserPath(alias, this);
        }

        @Override
        public RecipientGroupUserPath as(Table<?> alias) {
            return new RecipientGroupUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Messaging.MESSAGING;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RECIPIENT_GROUP_USER_RECIPIENT_GROUP_ID_IDX);
    }

    @Override
    public Identity<RecipientGroupUserRecord, Integer> getIdentity() {
        return (Identity<RecipientGroupUserRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RecipientGroupUserRecord> getPrimaryKey() {
        return Keys.RECIPIENT_GROUP_USER_PKEY;
    }

    @Override
    public List<ForeignKey<RecipientGroupUserRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RECIPIENT_GROUP_USER__RECIPIENT_GROUP_USER_RECIPIENT_GROUP_ID_FKEY);
    }

    private transient RecipientGroupPath _recipientGroup;

    /**
     * Get the implicit join path to the <code>messaging.recipient_group</code>
     * table.
     */
    public RecipientGroupPath recipientGroup() {
        if (_recipientGroup == null)
            _recipientGroup = new RecipientGroupPath(this, Keys.RECIPIENT_GROUP_USER__RECIPIENT_GROUP_USER_RECIPIENT_GROUP_ID_FKEY, null);

        return _recipientGroup;
    }

    @Override
    public RecipientGroupUser as(String alias) {
        return new RecipientGroupUser(DSL.name(alias), this);
    }

    @Override
    public RecipientGroupUser as(Name alias) {
        return new RecipientGroupUser(alias, this);
    }

    @Override
    public RecipientGroupUser as(Table<?> alias) {
        return new RecipientGroupUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientGroupUser rename(String name) {
        return new RecipientGroupUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientGroupUser rename(Name name) {
        return new RecipientGroupUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientGroupUser rename(Table<?> name) {
        return new RecipientGroupUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupUser where(Condition condition) {
        return new RecipientGroupUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientGroupUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientGroupUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientGroupUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientGroupUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
