/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.inovus.messaging.impl.jooq.Indexes;
import ru.inovus.messaging.impl.jooq.Keys;
import ru.inovus.messaging.impl.jooq.Messaging;
import ru.inovus.messaging.impl.jooq.tables.MessageTemplate.MessageTemplatePath;
import ru.inovus.messaging.impl.jooq.tables.RecipientGroup.RecipientGroupPath;
import ru.inovus.messaging.impl.jooq.tables.records.RecipientGroupTemplateRecord;


/**
 * Связь шаблонов с группой
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecipientGroupTemplate extends TableImpl<RecipientGroupTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>messaging.recipient_group_template</code>
     */
    public static final RecipientGroupTemplate RECIPIENT_GROUP_TEMPLATE = new RecipientGroupTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecipientGroupTemplateRecord> getRecordType() {
        return RecipientGroupTemplateRecord.class;
    }

    /**
     * The column <code>messaging.recipient_group_template.id</code>. Уникальный
     * идентификатор
     */
    public final TableField<RecipientGroupTemplateRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "Уникальный идентификатор");

    /**
     * The column
     * <code>messaging.recipient_group_template.recipient_group_id</code>.
     * Ссылка на группу
     */
    public final TableField<RecipientGroupTemplateRecord, Integer> RECIPIENT_GROUP_ID = createField(DSL.name("recipient_group_id"), SQLDataType.INTEGER.nullable(false), this, "Ссылка на группу");

    /**
     * The column
     * <code>messaging.recipient_group_template.message_template_id</code>.
     * Ссылка на шаблон
     */
    public final TableField<RecipientGroupTemplateRecord, Integer> MESSAGE_TEMPLATE_ID = createField(DSL.name("message_template_id"), SQLDataType.INTEGER.nullable(false), this, "Ссылка на шаблон");

    /**
     * The column
     * <code>messaging.recipient_group_template.message_template_code</code>.
     * Код на шаблона
     */
    public final TableField<RecipientGroupTemplateRecord, String> MESSAGE_TEMPLATE_CODE = createField(DSL.name("message_template_code"), SQLDataType.VARCHAR.nullable(false), this, "Код на шаблона");

    private RecipientGroupTemplate(Name alias, Table<RecipientGroupTemplateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RecipientGroupTemplate(Name alias, Table<RecipientGroupTemplateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Связь шаблонов с группой"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>messaging.recipient_group_template</code> table
     * reference
     */
    public RecipientGroupTemplate(String alias) {
        this(DSL.name(alias), RECIPIENT_GROUP_TEMPLATE);
    }

    /**
     * Create an aliased <code>messaging.recipient_group_template</code> table
     * reference
     */
    public RecipientGroupTemplate(Name alias) {
        this(alias, RECIPIENT_GROUP_TEMPLATE);
    }

    /**
     * Create a <code>messaging.recipient_group_template</code> table reference
     */
    public RecipientGroupTemplate() {
        this(DSL.name("recipient_group_template"), null);
    }

    public <O extends Record> RecipientGroupTemplate(Table<O> path, ForeignKey<O, RecipientGroupTemplateRecord> childPath, InverseForeignKey<O, RecipientGroupTemplateRecord> parentPath) {
        super(path, childPath, parentPath, RECIPIENT_GROUP_TEMPLATE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RecipientGroupTemplatePath extends RecipientGroupTemplate implements Path<RecipientGroupTemplateRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RecipientGroupTemplatePath(Table<O> path, ForeignKey<O, RecipientGroupTemplateRecord> childPath, InverseForeignKey<O, RecipientGroupTemplateRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RecipientGroupTemplatePath(Name alias, Table<RecipientGroupTemplateRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RecipientGroupTemplatePath as(String alias) {
            return new RecipientGroupTemplatePath(DSL.name(alias), this);
        }

        @Override
        public RecipientGroupTemplatePath as(Name alias) {
            return new RecipientGroupTemplatePath(alias, this);
        }

        @Override
        public RecipientGroupTemplatePath as(Table<?> alias) {
            return new RecipientGroupTemplatePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Messaging.MESSAGING;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RECIPIENT_GROUP_TEMPLATE_RECIPIENT_GROUP_ID_IDX);
    }

    @Override
    public Identity<RecipientGroupTemplateRecord, Integer> getIdentity() {
        return (Identity<RecipientGroupTemplateRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RecipientGroupTemplateRecord> getPrimaryKey() {
        return Keys.RECIPIENT_GROUP_TEMPLATE_PKEY;
    }

    @Override
    public List<ForeignKey<RecipientGroupTemplateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RECIPIENT_GROUP_TEMPLATE__RECIPIENT_GROUP_TEMPLATE_MESSAGE_TEMPLATE_CODE_FKEY, Keys.RECIPIENT_GROUP_TEMPLATE__RECIPIENT_GROUP_TEMPLATE_MESSAGE_TEMPLATE_ID_FKEY, Keys.RECIPIENT_GROUP_TEMPLATE__RECIPIENT_GROUP_TEMPLATE_RECIPIENT_GROUP_ID_FKEY);
    }

    private transient MessageTemplatePath _recipientGroupTemplateMessageTemplateCodeFkey;

    /**
     * Get the implicit join path to the <code>messaging.message_template</code>
     * table, via the
     * <code>recipient_group_template_message_template_code_fkey</code> key.
     */
    public MessageTemplatePath recipientGroupTemplateMessageTemplateCodeFkey() {
        if (_recipientGroupTemplateMessageTemplateCodeFkey == null)
            _recipientGroupTemplateMessageTemplateCodeFkey = new MessageTemplatePath(this, Keys.RECIPIENT_GROUP_TEMPLATE__RECIPIENT_GROUP_TEMPLATE_MESSAGE_TEMPLATE_CODE_FKEY, null);

        return _recipientGroupTemplateMessageTemplateCodeFkey;
    }

    private transient MessageTemplatePath _recipientGroupTemplateMessageTemplateIdFkey;

    /**
     * Get the implicit join path to the <code>messaging.message_template</code>
     * table, via the
     * <code>recipient_group_template_message_template_id_fkey</code> key.
     */
    public MessageTemplatePath recipientGroupTemplateMessageTemplateIdFkey() {
        if (_recipientGroupTemplateMessageTemplateIdFkey == null)
            _recipientGroupTemplateMessageTemplateIdFkey = new MessageTemplatePath(this, Keys.RECIPIENT_GROUP_TEMPLATE__RECIPIENT_GROUP_TEMPLATE_MESSAGE_TEMPLATE_ID_FKEY, null);

        return _recipientGroupTemplateMessageTemplateIdFkey;
    }

    private transient RecipientGroupPath _recipientGroup;

    /**
     * Get the implicit join path to the <code>messaging.recipient_group</code>
     * table.
     */
    public RecipientGroupPath recipientGroup() {
        if (_recipientGroup == null)
            _recipientGroup = new RecipientGroupPath(this, Keys.RECIPIENT_GROUP_TEMPLATE__RECIPIENT_GROUP_TEMPLATE_RECIPIENT_GROUP_ID_FKEY, null);

        return _recipientGroup;
    }

    @Override
    public RecipientGroupTemplate as(String alias) {
        return new RecipientGroupTemplate(DSL.name(alias), this);
    }

    @Override
    public RecipientGroupTemplate as(Name alias) {
        return new RecipientGroupTemplate(alias, this);
    }

    @Override
    public RecipientGroupTemplate as(Table<?> alias) {
        return new RecipientGroupTemplate(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientGroupTemplate rename(String name) {
        return new RecipientGroupTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientGroupTemplate rename(Name name) {
        return new RecipientGroupTemplate(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientGroupTemplate rename(Table<?> name) {
        return new RecipientGroupTemplate(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupTemplate where(Condition condition) {
        return new RecipientGroupTemplate(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupTemplate where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupTemplate where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupTemplate where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientGroupTemplate where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientGroupTemplate where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientGroupTemplate where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientGroupTemplate where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupTemplate whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientGroupTemplate whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
