/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.inovus.messaging.impl.jooq.Keys;
import ru.inovus.messaging.impl.jooq.Messaging;
import ru.inovus.messaging.impl.jooq.tables.Message.MessagePath;
import ru.inovus.messaging.impl.jooq.tables.MessageTemplate.MessageTemplatePath;
import ru.inovus.messaging.impl.jooq.tables.RecipientGroup.RecipientGroupPath;
import ru.inovus.messaging.impl.jooq.tables.records.TenantRecord;


/**
 * Тенанты
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tenant extends TableImpl<TenantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>messaging.tenant</code>
     */
    public static final Tenant TENANT = new Tenant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TenantRecord> getRecordType() {
        return TenantRecord.class;
    }

    /**
     * The column <code>messaging.tenant.code</code>. Уникальный код тенанта
     */
    public final TableField<TenantRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR.nullable(false), this, "Уникальный код тенанта");

    /**
     * The column <code>messaging.tenant.name</code>. Наименование тенанта
     */
    public final TableField<TenantRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR, this, "Наименование тенанта");

    private Tenant(Name alias, Table<TenantRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Tenant(Name alias, Table<TenantRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Тенанты"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>messaging.tenant</code> table reference
     */
    public Tenant(String alias) {
        this(DSL.name(alias), TENANT);
    }

    /**
     * Create an aliased <code>messaging.tenant</code> table reference
     */
    public Tenant(Name alias) {
        this(alias, TENANT);
    }

    /**
     * Create a <code>messaging.tenant</code> table reference
     */
    public Tenant() {
        this(DSL.name("tenant"), null);
    }

    public <O extends Record> Tenant(Table<O> path, ForeignKey<O, TenantRecord> childPath, InverseForeignKey<O, TenantRecord> parentPath) {
        super(path, childPath, parentPath, TENANT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TenantPath extends Tenant implements Path<TenantRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TenantPath(Table<O> path, ForeignKey<O, TenantRecord> childPath, InverseForeignKey<O, TenantRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TenantPath(Name alias, Table<TenantRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TenantPath as(String alias) {
            return new TenantPath(DSL.name(alias), this);
        }

        @Override
        public TenantPath as(Name alias) {
            return new TenantPath(alias, this);
        }

        @Override
        public TenantPath as(Table<?> alias) {
            return new TenantPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Messaging.MESSAGING;
    }

    @Override
    public UniqueKey<TenantRecord> getPrimaryKey() {
        return Keys.TENANT_PKEY;
    }

    private transient MessageTemplatePath _messageTemplate;

    /**
     * Get the implicit to-many join path to the
     * <code>messaging.message_template</code> table
     */
    public MessageTemplatePath messageTemplate() {
        if (_messageTemplate == null)
            _messageTemplate = new MessageTemplatePath(this, null, Keys.MESSAGE_TEMPLATE__MESSAGE_TEMPLATE_TENANT_CODE_FKEY.getInverseKey());

        return _messageTemplate;
    }

    private transient MessagePath _message;

    /**
     * Get the implicit to-many join path to the <code>messaging.message</code>
     * table
     */
    public MessagePath message() {
        if (_message == null)
            _message = new MessagePath(this, null, Keys.MESSAGE__MESSAGE_TENANT_CODE_FKEY.getInverseKey());

        return _message;
    }

    private transient RecipientGroupPath _recipientGroup;

    /**
     * Get the implicit to-many join path to the
     * <code>messaging.recipient_group</code> table
     */
    public RecipientGroupPath recipientGroup() {
        if (_recipientGroup == null)
            _recipientGroup = new RecipientGroupPath(this, null, Keys.RECIPIENT_GROUP__RECIPIENT_GROUP_TENANT_CODE_FKEY.getInverseKey());

        return _recipientGroup;
    }

    @Override
    public Tenant as(String alias) {
        return new Tenant(DSL.name(alias), this);
    }

    @Override
    public Tenant as(Name alias) {
        return new Tenant(alias, this);
    }

    @Override
    public Tenant as(Table<?> alias) {
        return new Tenant(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tenant rename(String name) {
        return new Tenant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tenant rename(Name name) {
        return new Tenant(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tenant rename(Table<?> name) {
        return new Tenant(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenant where(Condition condition) {
        return new Tenant(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenant where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenant where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenant where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tenant where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tenant where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tenant where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tenant where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenant whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tenant whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
