/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.inovus.messaging.impl.jooq.tables.Attachment;


/**
 * Вложения
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AttachmentRecord extends UpdatableRecordImpl<AttachmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>messaging.attachment.id</code>. Уникальный идентификатор
     * записи
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>messaging.attachment.id</code>. Уникальный идентификатор
     * записи
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>messaging.attachment.message_id</code>. Уникальный
     * идентификатор уведомления
     */
    public void setMessageId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>messaging.attachment.message_id</code>. Уникальный
     * идентификатор уведомления
     */
    public UUID getMessageId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>messaging.attachment.file</code>. Имя файла в хранилище
     */
    public void setFile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>messaging.attachment.file</code>. Имя файла в хранилище
     */
    public String getFile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>messaging.attachment.created_at</code>. Время создания
     * файла
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>messaging.attachment.created_at</code>. Время создания
     * файла
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttachmentRecord
     */
    public AttachmentRecord() {
        super(Attachment.ATTACHMENT);
    }

    /**
     * Create a detached, initialised AttachmentRecord
     */
    public AttachmentRecord(UUID id, UUID messageId, String file, LocalDateTime createdAt) {
        super(Attachment.ATTACHMENT);

        setId(id);
        setMessageId(messageId);
        setFile(file);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
