/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import ru.inovus.messaging.impl.jooq.tables.Component;


/**
 * Компоненты системы
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ComponentRecord extends UpdatableRecordImpl<ComponentRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -885985476;

    /**
     * Setter for <code>public.component.id</code>. Уникальный идентификатор
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.component.id</code>. Уникальный идентификатор
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.component.name</code>. Наименование компонента
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.component.name</code>. Наименование компонента
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Component.COMPONENT.ID;
    }

    @Override
    public Field<String> field2() {
        return Component.COMPONENT.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public ComponentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ComponentRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ComponentRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComponentRecord
     */
    public ComponentRecord() {
        super(Component.COMPONENT);
    }

    /**
     * Create a detached, initialised ComponentRecord
     */
    public ComponentRecord(Integer id, String name) {
        super(Component.COMPONENT);

        set(0, id);
        set(1, name);
    }
}
