/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.inovus.messaging.api.model.enums.MessageStatusType;
import ru.inovus.messaging.impl.jooq.tables.MessageRecipient;


/**
 * Получатель уведомления
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRecipientRecord extends UpdatableRecordImpl<MessageRecipientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>messaging.message_recipient.id</code>. Уникальный
     * идентификатор
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.id</code>. Уникальный
     * идентификатор
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>messaging.message_recipient.message_id</code>.
     * Идентификатор уведомления
     */
    public void setMessageId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.message_id</code>.
     * Идентификатор уведомления
     */
    public UUID getMessageId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>messaging.message_recipient.status_time</code>. Время
     * установки статуса
     */
    public void setStatusTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.status_time</code>. Время
     * установки статуса
     */
    public LocalDateTime getStatusTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>messaging.message_recipient.recipient_name</code>. Имя
     * контакта получателя
     */
    public void setRecipientName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.recipient_name</code>. Имя
     * контакта получателя
     */
    public String getRecipientName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>messaging.message_recipient.recipient_username</code>.
     * Уникальное имя пользователя из провайдера
     */
    public void setRecipientUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.recipient_username</code>.
     * Уникальное имя пользователя из провайдера
     */
    public String getRecipientUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>messaging.message_recipient.status</code>. Текущий
     * статус отправки уведомления получателю
     */
    public void setStatus(MessageStatusType value) {
        set(5, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.status</code>. Текущий
     * статус отправки уведомления получателю
     */
    public MessageStatusType getStatus() {
        return (MessageStatusType) get(5);
    }

    /**
     * Setter for <code>messaging.message_recipient.departured_at</code>. Дата и
     * время фактической отправки уведомления
     */
    public void setDeparturedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.departured_at</code>. Дата и
     * время фактической отправки уведомления
     */
    public LocalDateTime getDeparturedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>messaging.message_recipient.send_message_error</code>.
     * Сообщение ошибки отправки уведомления
     */
    public void setSendMessageError(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.send_message_error</code>.
     * Сообщение ошибки отправки уведомления
     */
    public String getSendMessageError() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecipientRecord
     */
    public MessageRecipientRecord() {
        super(MessageRecipient.MESSAGE_RECIPIENT);
    }

    /**
     * Create a detached, initialised MessageRecipientRecord
     */
    public MessageRecipientRecord(Long id, UUID messageId, LocalDateTime statusTime, String recipientName, String recipientUsername, MessageStatusType status, LocalDateTime departuredAt, String sendMessageError) {
        super(MessageRecipient.MESSAGE_RECIPIENT);

        setId(id);
        setMessageId(messageId);
        setStatusTime(statusTime);
        setRecipientName(recipientName);
        setRecipientUsername(recipientUsername);
        setStatus(status);
        setDeparturedAt(departuredAt);
        setSendMessageError(sendMessageError);
        resetChangedOnNotNull();
    }
}
