/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import ru.inovus.messaging.api.model.enums.AlertType;
import ru.inovus.messaging.api.model.enums.FormationType;
import ru.inovus.messaging.api.model.enums.RecipientType;
import ru.inovus.messaging.api.model.enums.Severity;
import ru.inovus.messaging.impl.jooq.tables.Message;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Уведомления
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record11<UUID, String, String, Severity, AlertType, LocalDateTime, String, FormationType, RecipientType, String, String> {

    private static final long serialVersionUID = -2020652857;

    /**
     * Setter for <code>messaging.message.id</code>. Уникальный идентификатор
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>messaging.message.id</code>. Уникальный идентификатор
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>messaging.message.caption</code>. Заголовок уведомления
     */
    public void setCaption(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>messaging.message.caption</code>. Заголовок уведомления
     */
    public String getCaption() {
        return (String) get(1);
    }

    /**
     * Setter for <code>messaging.message.text</code>. Содержимое уведомления
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>messaging.message.text</code>. Содержимое уведомления
     */
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>messaging.message.severity</code>. Важность уведомления
     */
    public void setSeverity(Severity value) {
        set(3, value);
    }

    /**
     * Getter for <code>messaging.message.severity</code>. Важность уведомления
     */
    public Severity getSeverity() {
        return (Severity) get(3);
    }

    /**
     * Setter for <code>messaging.message.alert_type</code>. Способ отображения уведомления
     */
    public void setAlertType(AlertType value) {
        set(4, value);
    }

    /**
     * Getter for <code>messaging.message.alert_type</code>. Способ отображения уведомления
     */
    public AlertType getAlertType() {
        return (AlertType) get(4);
    }

    /**
     * Setter for <code>messaging.message.sent_at</code>. Дата и время отправки уведомления
     */
    public void setSentAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>messaging.message.sent_at</code>. Дата и время отправки уведомления
     */
    public LocalDateTime getSentAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>messaging.message.tenant_code</code>. Тенант, к которому относится уведомление
     */
    public void setTenantCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>messaging.message.tenant_code</code>. Тенант, к которому относится уведомление
     */
    public String getTenantCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>messaging.message.formation_type</code>. Тип формирования уведомления
     */
    public void setFormationType(FormationType value) {
        set(7, value);
    }

    /**
     * Getter for <code>messaging.message.formation_type</code>. Тип формирования уведомления
     */
    public FormationType getFormationType() {
        return (FormationType) get(7);
    }

    /**
     * Setter for <code>messaging.message.recipient_type</code>. Тип получателя уведомления
     */
    public void setRecipientType(RecipientType value) {
        set(8, value);
    }

    /**
     * Getter for <code>messaging.message.recipient_type</code>. Тип получателя уведомления
     */
    public RecipientType getRecipientType() {
        return (RecipientType) get(8);
    }

    /**
     * Setter for <code>messaging.message.notification_type</code>. Код шаблона, который был использован для формирования уведомления
     */
    public void setNotificationType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>messaging.message.notification_type</code>. Код шаблона, который был использован для формирования уведомления
     */
    public String getNotificationType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>messaging.message.channel_id</code>. Идентификатор канала отправки уведомления
     */
    public void setChannelId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>messaging.message.channel_id</code>. Идентификатор канала отправки уведомления
     */
    public String getChannelId() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<UUID, String, String, Severity, AlertType, LocalDateTime, String, FormationType, RecipientType, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<UUID, String, String, Severity, AlertType, LocalDateTime, String, FormationType, RecipientType, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Message.MESSAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return Message.MESSAGE.CAPTION;
    }

    @Override
    public Field<String> field3() {
        return Message.MESSAGE.TEXT;
    }

    @Override
    public Field<Severity> field4() {
        return Message.MESSAGE.SEVERITY;
    }

    @Override
    public Field<AlertType> field5() {
        return Message.MESSAGE.ALERT_TYPE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Message.MESSAGE.SENT_AT;
    }

    @Override
    public Field<String> field7() {
        return Message.MESSAGE.TENANT_CODE;
    }

    @Override
    public Field<FormationType> field8() {
        return Message.MESSAGE.FORMATION_TYPE;
    }

    @Override
    public Field<RecipientType> field9() {
        return Message.MESSAGE.RECIPIENT_TYPE;
    }

    @Override
    public Field<String> field10() {
        return Message.MESSAGE.NOTIFICATION_TYPE;
    }

    @Override
    public Field<String> field11() {
        return Message.MESSAGE.CHANNEL_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCaption();
    }

    @Override
    public String component3() {
        return getText();
    }

    @Override
    public Severity component4() {
        return getSeverity();
    }

    @Override
    public AlertType component5() {
        return getAlertType();
    }

    @Override
    public LocalDateTime component6() {
        return getSentAt();
    }

    @Override
    public String component7() {
        return getTenantCode();
    }

    @Override
    public FormationType component8() {
        return getFormationType();
    }

    @Override
    public RecipientType component9() {
        return getRecipientType();
    }

    @Override
    public String component10() {
        return getNotificationType();
    }

    @Override
    public String component11() {
        return getChannelId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCaption();
    }

    @Override
    public String value3() {
        return getText();
    }

    @Override
    public Severity value4() {
        return getSeverity();
    }

    @Override
    public AlertType value5() {
        return getAlertType();
    }

    @Override
    public LocalDateTime value6() {
        return getSentAt();
    }

    @Override
    public String value7() {
        return getTenantCode();
    }

    @Override
    public FormationType value8() {
        return getFormationType();
    }

    @Override
    public RecipientType value9() {
        return getRecipientType();
    }

    @Override
    public String value10() {
        return getNotificationType();
    }

    @Override
    public String value11() {
        return getChannelId();
    }

    @Override
    public MessageRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public MessageRecord value2(String value) {
        setCaption(value);
        return this;
    }

    @Override
    public MessageRecord value3(String value) {
        setText(value);
        return this;
    }

    @Override
    public MessageRecord value4(Severity value) {
        setSeverity(value);
        return this;
    }

    @Override
    public MessageRecord value5(AlertType value) {
        setAlertType(value);
        return this;
    }

    @Override
    public MessageRecord value6(LocalDateTime value) {
        setSentAt(value);
        return this;
    }

    @Override
    public MessageRecord value7(String value) {
        setTenantCode(value);
        return this;
    }

    @Override
    public MessageRecord value8(FormationType value) {
        setFormationType(value);
        return this;
    }

    @Override
    public MessageRecord value9(RecipientType value) {
        setRecipientType(value);
        return this;
    }

    @Override
    public MessageRecord value10(String value) {
        setNotificationType(value);
        return this;
    }

    @Override
    public MessageRecord value11(String value) {
        setChannelId(value);
        return this;
    }

    @Override
    public MessageRecord values(UUID value1, String value2, String value3, Severity value4, AlertType value5, LocalDateTime value6, String value7, FormationType value8, RecipientType value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(UUID id, String caption, String text, Severity severity, AlertType alertType, LocalDateTime sentAt, String tenantCode, FormationType formationType, RecipientType recipientType, String notificationType, String channelId) {
        super(Message.MESSAGE);

        set(0, id);
        set(1, caption);
        set(2, text);
        set(3, severity);
        set(4, alertType);
        set(5, sentAt);
        set(6, tenantCode);
        set(7, formationType);
        set(8, recipientType);
        set(9, notificationType);
        set(10, channelId);
    }
}
