/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.inovus.messaging.api.model.enums.AlertType;
import ru.inovus.messaging.api.model.enums.Severity;
import ru.inovus.messaging.impl.jooq.tables.MessageTemplate;


/**
 * Шаблоны уведомлений
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageTemplateRecord extends UpdatableRecordImpl<MessageTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>messaging.message_template.id</code>. Уникальный
     * идентификатор
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>messaging.message_template.id</code>. Уникальный
     * идентификатор
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>messaging.message_template.caption</code>. Заголовок
     * уведомления
     */
    public void setCaption(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>messaging.message_template.caption</code>. Заголовок
     * уведомления
     */
    public String getCaption() {
        return (String) get(1);
    }

    /**
     * Setter for <code>messaging.message_template.text</code>. Содержимое
     * уведомления
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>messaging.message_template.text</code>. Содержимое
     * уведомления
     */
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>messaging.message_template.severity</code>. Важность
     * уведомления
     */
    public void setSeverity(Severity value) {
        set(3, value);
    }

    /**
     * Getter for <code>messaging.message_template.severity</code>. Важность
     * уведомления
     */
    public Severity getSeverity() {
        return (Severity) get(3);
    }

    /**
     * Setter for <code>messaging.message_template.alert_type</code>. Способ
     * отображения уведомления
     */
    public void setAlertType(AlertType value) {
        set(4, value);
    }

    /**
     * Getter for <code>messaging.message_template.alert_type</code>. Способ
     * отображения уведомления
     */
    public AlertType getAlertType() {
        return (AlertType) get(4);
    }

    /**
     * Setter for <code>messaging.message_template.name</code>. Наименование
     * шаблона уведомления
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>messaging.message_template.name</code>. Наименование
     * шаблона уведомления
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>messaging.message_template.enabled</code>. Признак
     * включения уведомления
     */
    public void setEnabled(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>messaging.message_template.enabled</code>. Признак
     * включения уведомления
     */
    public Boolean getEnabled() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>messaging.message_template.code</code>. Код шаблона
     * уведомления
     */
    public void setCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>messaging.message_template.code</code>. Код шаблона
     * уведомления
     */
    public String getCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>messaging.message_template.channel_code</code>. Код
     * канала отправки уведомления
     */
    public void setChannelCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>messaging.message_template.channel_code</code>. Код
     * канала отправки уведомления
     */
    public String getChannelCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>messaging.message_template.tenant_code</code>. Тенант, к
     * которому относится настройка
     */
    public void setTenantCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>messaging.message_template.tenant_code</code>. Тенант, к
     * которому относится настройка
     */
    public String getTenantCode() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageTemplateRecord
     */
    public MessageTemplateRecord() {
        super(MessageTemplate.MESSAGE_TEMPLATE);
    }

    /**
     * Create a detached, initialised MessageTemplateRecord
     */
    public MessageTemplateRecord(Integer id, String caption, String text, Severity severity, AlertType alertType, String name, Boolean enabled, String code, String channelCode, String tenantCode) {
        super(MessageTemplate.MESSAGE_TEMPLATE);

        setId(id);
        setCaption(caption);
        setText(text);
        setSeverity(severity);
        setAlertType(alertType);
        setName(name);
        setEnabled(enabled);
        setCode(code);
        setChannelCode(channelCode);
        setTenantCode(tenantCode);
        resetChangedOnNotNull();
    }
}
