/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;

import ru.inovus.messaging.api.model.AlertType;
import ru.inovus.messaging.api.model.FormationType;
import ru.inovus.messaging.api.model.RecipientType;
import ru.inovus.messaging.api.model.Severity;
import ru.inovus.messaging.impl.jooq.tables.Message;


/**
 * Сообщения
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record17<UUID, String, String, Severity, AlertType, LocalDateTime, String, Integer, FormationType, RecipientType, String, String, String, Boolean, Boolean, LocalDateTime, String> {

    private static final long serialVersionUID = 394716327;

    /**
     * Setter for <code>public.message.id</code>. Уникальный идентификатор
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.message.id</code>. Уникальный идентификатор
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.message.caption</code>. Заголовок
     */
    public void setCaption(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.message.caption</code>. Заголовок
     */
    public String getCaption() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.message.text</code>. Содержимое сообщения
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.message.text</code>. Содержимое сообщения
     */
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.message.severity</code>. Жесткость сообщения
     */
    public void setSeverity(Severity value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.message.severity</code>. Жесткость сообщения
     */
    public Severity getSeverity() {
        return (Severity) get(3);
    }

    /**
     * Setter for <code>public.message.alert_type</code>. Тип предупреждения
     */
    public void setAlertType(AlertType value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.message.alert_type</code>. Тип предупреждения
     */
    public AlertType getAlertType() {
        return (AlertType) get(4);
    }

    /**
     * Setter for <code>public.message.sent_at</code>. Отправлено (дата и время)
     */
    public void setSentAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.message.sent_at</code>. Отправлено (дата и время)
     */
    public LocalDateTime getSentAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.message.system_id</code>. Идентификатор системы
     */
    public void setSystemId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.message.system_id</code>. Идентификатор системы
     */
    public String getSystemId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.message.component_id</code>. Компонент Системы, к которому относится уведомление
     */
    public void setComponentId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.message.component_id</code>. Компонент Системы, к которому относится уведомление
     */
    public Integer getComponentId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.message.formation_type</code>. Тип формирования уведомления
     */
    public void setFormationType(FormationType value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.message.formation_type</code>. Тип формирования уведомления
     */
    public FormationType getFormationType() {
        return (FormationType) get(8);
    }

    /**
     * Setter for <code>public.message.recipient_type</code>.
     */
    public void setRecipientType(RecipientType value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.message.recipient_type</code>.
     */
    public RecipientType getRecipientType() {
        return (RecipientType) get(9);
    }

    /**
     * Setter for <code>public.message.notification_type</code>.
     */
    public void setNotificationType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.message.notification_type</code>.
     */
    public String getNotificationType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.message.object_id</code>.
     */
    public void setObjectId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.message.object_id</code>.
     */
    public String getObjectId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.message.object_type</code>.
     */
    public void setObjectType(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.message.object_type</code>.
     */
    public String getObjectType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.message.send_notice</code>.
     */
    public void setSendNotice(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.message.send_notice</code>.
     */
    public Boolean getSendNotice() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.message.send_email</code>.
     */
    public void setSendEmail(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.message.send_email</code>.
     */
    public Boolean getSendEmail() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.message.send_email_date</code>. Дата и время отправки email
     */
    public void setSendEmailDate(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.message.send_email_date</code>. Дата и время отправки email
     */
    public LocalDateTime getSendEmailDate() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.message.send_email_error</code>. Ошибка, возникшая при последней попытке отправки email
     */
    public void setSendEmailError(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.message.send_email_error</code>. Ошибка, возникшая при последней попытке отправки email
     */
    public String getSendEmailError() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<UUID, String, String, Severity, AlertType, LocalDateTime, String, Integer, FormationType, RecipientType, String, String, String, Boolean, Boolean, LocalDateTime, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<UUID, String, String, Severity, AlertType, LocalDateTime, String, Integer, FormationType, RecipientType, String, String, String, Boolean, Boolean, LocalDateTime, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Message.MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Message.MESSAGE.CAPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Message.MESSAGE.TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Severity> field4() {
        return Message.MESSAGE.SEVERITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<AlertType> field5() {
        return Message.MESSAGE.ALERT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return Message.MESSAGE.SENT_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Message.MESSAGE.SYSTEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Message.MESSAGE.COMPONENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<FormationType> field9() {
        return Message.MESSAGE.FORMATION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<RecipientType> field10() {
        return Message.MESSAGE.RECIPIENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Message.MESSAGE.NOTIFICATION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Message.MESSAGE.OBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Message.MESSAGE.OBJECT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return Message.MESSAGE.SEND_NOTICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field15() {
        return Message.MESSAGE.SEND_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field16() {
        return Message.MESSAGE.SEND_EMAIL_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Message.MESSAGE.SEND_EMAIL_ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCaption();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Severity component4() {
        return getSeverity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlertType component5() {
        return getAlertType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getSentAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSystemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getComponentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormationType component9() {
        return getFormationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipientType component10() {
        return getRecipientType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getNotificationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getObjectType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getSendNotice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component15() {
        return getSendEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component16() {
        return getSendEmailDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getSendEmailError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCaption();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Severity value4() {
        return getSeverity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlertType value5() {
        return getAlertType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getSentAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSystemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getComponentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormationType value9() {
        return getFormationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipientType value10() {
        return getRecipientType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getNotificationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getObjectType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getSendNotice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value15() {
        return getSendEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value16() {
        return getSendEmailDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getSendEmailError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value2(String value) {
        setCaption(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value3(String value) {
        setText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value4(Severity value) {
        setSeverity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value5(AlertType value) {
        setAlertType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value6(LocalDateTime value) {
        setSentAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value7(String value) {
        setSystemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value8(Integer value) {
        setComponentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value9(FormationType value) {
        setFormationType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value10(RecipientType value) {
        setRecipientType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value11(String value) {
        setNotificationType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value12(String value) {
        setObjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value13(String value) {
        setObjectType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value14(Boolean value) {
        setSendNotice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value15(Boolean value) {
        setSendEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value16(LocalDateTime value) {
        setSendEmailDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value17(String value) {
        setSendEmailError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord values(UUID value1, String value2, String value3, Severity value4, AlertType value5, LocalDateTime value6, String value7, Integer value8, FormationType value9, RecipientType value10, String value11, String value12, String value13, Boolean value14, Boolean value15, LocalDateTime value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(UUID id, String caption, String text, Severity severity, AlertType alertType, LocalDateTime sentAt, String systemId, Integer componentId, FormationType formationType, RecipientType recipientType, String notificationType, String objectId, String objectType, Boolean sendNotice, Boolean sendEmail, LocalDateTime sendEmailDate, String sendEmailError) {
        super(Message.MESSAGE);

        set(0, id);
        set(1, caption);
        set(2, text);
        set(3, severity);
        set(4, alertType);
        set(5, sentAt);
        set(6, systemId);
        set(7, componentId);
        set(8, formationType);
        set(9, recipientType);
        set(10, notificationType);
        set(11, objectId);
        set(12, objectType);
        set(13, sendNotice);
        set(14, sendEmail);
        set(15, sendEmailDate);
        set(16, sendEmailError);
    }
}
