/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import ru.inovus.messaging.impl.jooq.tables.MessageRecipient;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * Получатель уведомления
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecipientRecord extends UpdatableRecordImpl<MessageRecipientRecord> implements Record5<Integer, UUID, LocalDateTime, String, String> {

    private static final long serialVersionUID = -787415833;

    /**
     * Setter for <code>messaging.message_recipient.id</code>. Уникальный идентификатор
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.id</code>. Уникальный идентификатор
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>messaging.message_recipient.message_id</code>. Идентификатор уведомления
     */
    public void setMessageId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.message_id</code>. Идентификатор уведомления
     */
    public UUID getMessageId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>messaging.message_recipient.read_at</code>. Дата и время прочтения уведомления
     */
    public void setReadAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.read_at</code>. Дата и время прочтения уведомления
     */
    public LocalDateTime getReadAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>messaging.message_recipient.recipient_name</code>. Имя контакта получателя
     */
    public void setRecipientName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.recipient_name</code>. Имя контакта получателя
     */
    public String getRecipientName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>messaging.message_recipient.recipient_send_channel_id</code>. Идентификатор получателя в формате канала доставки
     */
    public void setRecipientSendChannelId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>messaging.message_recipient.recipient_send_channel_id</code>. Идентификатор получателя в формате канала доставки
     */
    public String getRecipientSendChannelId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, UUID, LocalDateTime, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, UUID, LocalDateTime, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MessageRecipient.MESSAGE_RECIPIENT.ID;
    }

    @Override
    public Field<UUID> field2() {
        return MessageRecipient.MESSAGE_RECIPIENT.MESSAGE_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return MessageRecipient.MESSAGE_RECIPIENT.READ_AT;
    }

    @Override
    public Field<String> field4() {
        return MessageRecipient.MESSAGE_RECIPIENT.RECIPIENT_NAME;
    }

    @Override
    public Field<String> field5() {
        return MessageRecipient.MESSAGE_RECIPIENT.RECIPIENT_SEND_CHANNEL_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getMessageId();
    }

    @Override
    public LocalDateTime component3() {
        return getReadAt();
    }

    @Override
    public String component4() {
        return getRecipientName();
    }

    @Override
    public String component5() {
        return getRecipientSendChannelId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getMessageId();
    }

    @Override
    public LocalDateTime value3() {
        return getReadAt();
    }

    @Override
    public String value4() {
        return getRecipientName();
    }

    @Override
    public String value5() {
        return getRecipientSendChannelId();
    }

    @Override
    public MessageRecipientRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MessageRecipientRecord value2(UUID value) {
        setMessageId(value);
        return this;
    }

    @Override
    public MessageRecipientRecord value3(LocalDateTime value) {
        setReadAt(value);
        return this;
    }

    @Override
    public MessageRecipientRecord value4(String value) {
        setRecipientName(value);
        return this;
    }

    @Override
    public MessageRecipientRecord value5(String value) {
        setRecipientSendChannelId(value);
        return this;
    }

    @Override
    public MessageRecipientRecord values(Integer value1, UUID value2, LocalDateTime value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecipientRecord
     */
    public MessageRecipientRecord() {
        super(MessageRecipient.MESSAGE_RECIPIENT);
    }

    /**
     * Create a detached, initialised MessageRecipientRecord
     */
    public MessageRecipientRecord(Integer id, UUID messageId, LocalDateTime readAt, String recipientName, String recipientSendChannelId) {
        super(MessageRecipient.MESSAGE_RECIPIENT);

        set(0, id);
        set(1, messageId);
        set(2, readAt);
        set(3, recipientName);
        set(4, recipientSendChannelId);
    }
}
