/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.inovus.messaging.impl.jooq.tables.RecipientGroupTemplate;


/**
 * Связь шаблонов с группой
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecipientGroupTemplateRecord extends UpdatableRecordImpl<RecipientGroupTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>messaging.recipient_group_template.id</code>. Уникальный
     * идентификатор
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>messaging.recipient_group_template.id</code>. Уникальный
     * идентификатор
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>messaging.recipient_group_template.recipient_group_id</code>.
     * Ссылка на группу
     */
    public void setRecipientGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>messaging.recipient_group_template.recipient_group_id</code>.
     * Ссылка на группу
     */
    public Integer getRecipientGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>messaging.recipient_group_template.message_template_id</code>.
     * Ссылка на шаблон
     */
    public void setMessageTemplateId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>messaging.recipient_group_template.message_template_id</code>.
     * Ссылка на шаблон
     */
    public Integer getMessageTemplateId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>messaging.recipient_group_template.message_template_code</code>.
     * Код на шаблона
     */
    public void setMessageTemplateCode(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>messaging.recipient_group_template.message_template_code</code>.
     * Код на шаблона
     */
    public String getMessageTemplateCode() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipientGroupTemplateRecord
     */
    public RecipientGroupTemplateRecord() {
        super(RecipientGroupTemplate.RECIPIENT_GROUP_TEMPLATE);
    }

    /**
     * Create a detached, initialised RecipientGroupTemplateRecord
     */
    public RecipientGroupTemplateRecord(Integer id, Integer recipientGroupId, Integer messageTemplateId, String messageTemplateCode) {
        super(RecipientGroupTemplate.RECIPIENT_GROUP_TEMPLATE);

        setId(id);
        setRecipientGroupId(recipientGroupId);
        setMessageTemplateId(messageTemplateId);
        setMessageTemplateCode(messageTemplateCode);
        resetChangedOnNotNull();
    }
}
