/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.inovus.messaging.impl.jooq.tables.RecipientGroupUser;


/**
 * Связь получателей с группой
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecipientGroupUserRecord extends UpdatableRecordImpl<RecipientGroupUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>messaging.recipient_group_user.id</code>. Уникальный
     * идентификатор
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>messaging.recipient_group_user.id</code>. Уникальный
     * идентификатор
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>messaging.recipient_group_user.recipient_group_id</code>. Ссылка на
     * группу
     */
    public void setRecipientGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>messaging.recipient_group_user.recipient_group_id</code>. Ссылка на
     * группу
     */
    public Integer getRecipientGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>messaging.recipient_group_user.recipient_name</code>.
     * Имя получателя
     */
    public void setRecipientName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>messaging.recipient_group_user.recipient_name</code>.
     * Имя получателя
     */
    public String getRecipientName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>messaging.recipient_group_user.recipient_username</code>. ID
     * получателя
     */
    public void setRecipientUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>messaging.recipient_group_user.recipient_username</code>. ID
     * получателя
     */
    public String getRecipientUsername() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipientGroupUserRecord
     */
    public RecipientGroupUserRecord() {
        super(RecipientGroupUser.RECIPIENT_GROUP_USER);
    }

    /**
     * Create a detached, initialised RecipientGroupUserRecord
     */
    public RecipientGroupUserRecord(Integer id, Integer recipientGroupId, String recipientName, String recipientUsername) {
        super(RecipientGroupUser.RECIPIENT_GROUP_USER);

        setId(id);
        setRecipientGroupId(recipientGroupId);
        setRecipientName(recipientName);
        setRecipientUsername(recipientUsername);
        resetChangedOnNotNull();
    }
}
