/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.inovus.messaging.impl.jooq.tables.RecipientGroup;


/**
 * Группы получателей
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecipientGroupRecord extends UpdatableRecordImpl<RecipientGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>messaging.recipient_group.id</code>. Уникальный
     * идентификатор
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>messaging.recipient_group.id</code>. Уникальный
     * идентификатор
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>messaging.recipient_group.name</code>. Наименование
     * группы
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>messaging.recipient_group.name</code>. Наименование
     * группы
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>messaging.recipient_group.description</code>. Описание
     * группы
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>messaging.recipient_group.description</code>. Описание
     * группы
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>messaging.recipient_group.tenant_code</code>.
     */
    public void setTenantCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>messaging.recipient_group.tenant_code</code>.
     */
    public String getTenantCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>messaging.recipient_group.code</code>. Код группы
     */
    public void setCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>messaging.recipient_group.code</code>. Код группы
     */
    public String getCode() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipientGroupRecord
     */
    public RecipientGroupRecord() {
        super(RecipientGroup.RECIPIENT_GROUP);
    }

    /**
     * Create a detached, initialised RecipientGroupRecord
     */
    public RecipientGroupRecord(Integer id, String name, String description, String tenantCode, String code) {
        super(RecipientGroup.RECIPIENT_GROUP);

        setId(id);
        setName(name);
        setDescription(description);
        setTenantCode(tenantCode);
        setCode(code);
        resetChangedOnNotNull();
    }
}
