/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.inovus.messaging.impl.jooq.tables.Tenant;


/**
 * Тенанты
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TenantRecord extends UpdatableRecordImpl<TenantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>messaging.tenant.code</code>. Уникальный код тенанта
     */
    public void setCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>messaging.tenant.code</code>. Уникальный код тенанта
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>messaging.tenant.name</code>. Наименование тенанта
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>messaging.tenant.name</code>. Наименование тенанта
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TenantRecord
     */
    public TenantRecord() {
        super(Tenant.TENANT);
    }

    /**
     * Create a detached, initialised TenantRecord
     */
    public TenantRecord(String code, String name) {
        super(Tenant.TENANT);

        setCode(code);
        setName(name);
        resetChangedOnNotNull();
    }
}
