/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import ru.inovus.messaging.api.model.AlertType;
import ru.inovus.messaging.api.model.InfoType;
import ru.inovus.messaging.impl.jooq.tables.UserSetting;

import javax.annotation.Generated;


/**
 * Пользовательские настройки уведомлений
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettingRecord extends UpdatableRecordImpl<UserSettingRecord> implements Record5<Integer, AlertType, InfoType, Boolean, String> {

    private static final long serialVersionUID = -2140099988;

    /**
     * Setter for <code>public.user_setting.id</code>. Уникальный идентификатор
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_setting.id</code>. Уникальный идентификатор
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_setting.alert_type</code>. Тип предупреждения
     */
    public void setAlertType(AlertType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_setting.alert_type</code>. Тип предупреждения
     */
    public AlertType getAlertType() {
        return (AlertType) get(1);
    }

    /**
     * Setter for <code>public.user_setting.info_type</code>. Вид информирования по событию (почта, центр уведомления)
     */
    public void setInfoType(InfoType value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_setting.info_type</code>. Вид информирования по событию (почта, центр уведомления)
     */
    public InfoType getInfoType() {
        return (InfoType) get(2);
    }

    /**
     * Setter for <code>public.user_setting.is_disabled</code>. Признак выключения уведомления
     */
    public void setIsDisabled(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_setting.is_disabled</code>. Признак выключения уведомления
     */
    public Boolean getIsDisabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.user_setting.user_id</code>. Идентификатор пользователя
     */
    public void setUserId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_setting.user_id</code>. Идентификатор пользователя
     */
    public String getUserId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, AlertType, InfoType, Boolean, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, AlertType, InfoType, Boolean, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserSetting.USER_SETTING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<AlertType> field2() {
        return UserSetting.USER_SETTING.ALERT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<InfoType> field3() {
        return UserSetting.USER_SETTING.INFO_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return UserSetting.USER_SETTING.IS_DISABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserSetting.USER_SETTING.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlertType component2() {
        return getAlertType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InfoType component3() {
        return getInfoType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlertType value2() {
        return getAlertType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InfoType value3() {
        return getInfoType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value2(AlertType value) {
        setAlertType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value3(InfoType value) {
        setInfoType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value4(Boolean value) {
        setIsDisabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value5(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord values(Integer value1, AlertType value2, InfoType value3, Boolean value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSettingRecord
     */
    public UserSettingRecord() {
        super(UserSetting.USER_SETTING);
    }

    /**
     * Create a detached, initialised UserSettingRecord
     */
    public UserSettingRecord(Integer id, AlertType alertType, InfoType infoType, Boolean isDisabled, String userId) {
        super(UserSetting.USER_SETTING);

        set(0, id);
        set(1, alertType);
        set(2, infoType);
        set(3, isDisabled);
        set(4, userId);
    }
}
