/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.inovus.messaging.api.model.AlertType;
import ru.inovus.messaging.impl.jooq.tables.UserSetting;


/**
 * Пользовательские настройки уведомлений
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettingRecord extends UpdatableRecordImpl<UserSettingRecord> implements Record7<Integer, AlertType, Boolean, String, Boolean, Boolean, Integer> {

    private static final long serialVersionUID = -997629707;

    /**
     * Setter for <code>public.user_setting.id</code>. Уникальный идентификатор
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_setting.id</code>. Уникальный идентификатор
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_setting.alert_type</code>. Тип предупреждения
     */
    public void setAlertType(AlertType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_setting.alert_type</code>. Тип предупреждения
     */
    public AlertType getAlertType() {
        return (AlertType) get(1);
    }

    /**
     * Setter for <code>public.user_setting.is_disabled</code>. Признак выключения уведомления
     */
    public void setIsDisabled(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_setting.is_disabled</code>. Признак выключения уведомления
     */
    public Boolean getIsDisabled() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.user_setting.user_id</code>. Идентификатор пользователя
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_setting.user_id</code>. Идентификатор пользователя
     */
    public String getUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user_setting.send_notice</code>.
     */
    public void setSendNotice(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_setting.send_notice</code>.
     */
    public Boolean getSendNotice() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.user_setting.send_email</code>.
     */
    public void setSendEmail(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_setting.send_email</code>.
     */
    public Boolean getSendEmail() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.user_setting.msg_setting_id</code>.
     */
    public void setMsgSettingId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_setting.msg_setting_id</code>.
     */
    public Integer getMsgSettingId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, AlertType, Boolean, String, Boolean, Boolean, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, AlertType, Boolean, String, Boolean, Boolean, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserSetting.USER_SETTING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<AlertType> field2() {
        return UserSetting.USER_SETTING.ALERT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return UserSetting.USER_SETTING.IS_DISABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserSetting.USER_SETTING.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return UserSetting.USER_SETTING.SEND_NOTICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return UserSetting.USER_SETTING.SEND_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return UserSetting.USER_SETTING.MSG_SETTING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlertType component2() {
        return getAlertType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getIsDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getSendNotice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getSendEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getMsgSettingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlertType value2() {
        return getAlertType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getIsDisabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getSendNotice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getSendEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getMsgSettingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value2(AlertType value) {
        setAlertType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value3(Boolean value) {
        setIsDisabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value4(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value5(Boolean value) {
        setSendNotice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value6(Boolean value) {
        setSendEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord value7(Integer value) {
        setMsgSettingId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSettingRecord values(Integer value1, AlertType value2, Boolean value3, String value4, Boolean value5, Boolean value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSettingRecord
     */
    public UserSettingRecord() {
        super(UserSetting.USER_SETTING);
    }

    /**
     * Create a detached, initialised UserSettingRecord
     */
    public UserSettingRecord(Integer id, AlertType alertType, Boolean isDisabled, String userId, Boolean sendNotice, Boolean sendEmail, Integer msgSettingId) {
        super(UserSetting.USER_SETTING);

        set(0, id);
        set(1, alertType);
        set(2, isDisabled);
        set(3, userId);
        set(4, sendNotice);
        set(5, sendEmail);
        set(6, msgSettingId);
    }
}
