// Generated by CoffeeScript 1.10.0
(function() {
  define(['underscore', 'backbone', 'jquery', 'infect'], function(_, Backbone, $, infect) {
    'use strict';
    return Backbone.View.extend({
      DEBUG: false,
      WS_URL: '',
      REST_URL: '',
      dataKey: 'notification_data',
      workerKey: 'worker_key',
      requestCountKey: 'request_count',
      election_key: 'election_is_started',
      worker: false,
      store_interval: null,
      myTabId: '',
      ticker: null,
      checker: null,
      idsToConfirm: [],
      fullscreenConfirmKey: "fullscreenMessageConfirm",
      hintMessageConfirmKey: 'hintConfirm',
      hintMessages: {
        boxes: []
      },
      fullScreenElementId: 'fullscreen-message__wrapper',
      popupElementId: 'pop-message__wrapper',
      className: 'notificationElement',
      initGame: 'startElection',
      events: {
        'click .popup-message__button--close': function(e) {
          localStorage[this.hintMessageConfirmKey] = e.currentTarget.dataset.boxid;
          this.confirmReading(+e.currentTarget.dataset.messageid);
          this.closeHintMessage(+e.currentTarget.dataset.boxid);
        },
        'click .popup-message-miniicons__iconbox': function(e) {
          this.gotoHintMessage(+e.currentTarget.dataset.boxid);
          this.$el.find('.popup-message-miniicons__iconbox').removeClass('popup-message-miniicons__iconbox--active');
          e.currentTarget.className += ' popup-message-miniicons__iconbox--active';
        },
        'click #fullscreenMessageConfirmButton': function(e) {
          this.confirmAllFullscreenMessages();
        }
      },
      initialize: function(target, view) {
        this.WS_URL = this.options.address.ws + '/ws';
        this.REST_URL = this.options.address.rest;
        this.render();
        this.clearLocalStorageVars();
        this.setStorageListeners();
        window.application.once('initialized', (function(_this) {
          return function() {
            localStorage[_this.requestCountKey] = '';
            localStorage[_this.requestCountKey] = 'true';
            return _this.runChecker();
          };
        })(this));
      },
      setStorageListeners: function() {
        window.addEventListener('storage', (function(_this) {
          return function(e) {
            if (e.key === _this.requestCountKey && localStorage[_this.requestCountKey] !== '') {
                _this.requestCount();
                return;
            }
            if (e.key === _this.dataKey && localStorage[_this.dataKey] !== '') {
              _this.DEBUG && _this.log('пришло сообщение', e.newValue);
              _this.showMessage(JSON.parse(e.newValue));
              return;
            }
            if (e.key === _this.election_key && localStorage[_this.election_key] === 'true') {
              _this.runElection();
              return;
            }
            if (e.key === _this.fullscreenConfirmKey && localStorage[_this.fullscreenConfirmKey] === 'done') {
              localStorage[_this.fullscreenConfirmKey] = "";
              _this.$el.find('#' + _this.fullScreenElementId).html('');
              return;
            }
            if (e.key === _this.hintMessageConfirmKey && localStorage[_this.hintMessageConfirmKey] !== '') {
              _this.closeHintMessage(+localStorage[_this.hintMessageConfirmKey]);
              localStorage[_this.hintMessageConfirmKey] = "";
              return;
            }
          };
        })(this));
      },
      clearLocalStorageVars: function() {
        this.removeElection();
        localStorage[this.workerKey] = "";
        localStorage[this.dataKey] = "";
        localStorage[this.fullscreenConfirmKey] = "";
        localStorage[this.hintMessageConfirmKey] = "";
      },
      showMessage: function(message) {
        var page = window.application.getActivePage();
        if (page && page.options.id === 'messaging_message_list') {
          var region = page.getRegions()[0];
          if (region) {
              var cont = region.getContainer('main');
              if (cont) {
                  cont.widget().triggerMethod('updateQuery');
              }
          }
        }
        switch (message.alertType) {
          case "BLOCKER":
            this.renderOrAddFullscreenMessage(message);
            break;
          case "POPUP":
            this.renderHintMessages(message);
            break;
          default:
            if (typeof message.count === 'number') {
              this.updateCounter(message);
            }
        }
      },
      updateCounter: function(message) {
        infect.get('Header').updateNotifyCounter(message.count);
      },
      render: function() {
        this.$el.append('<div id="' + this.fullScreenElementId + '"></div>');
        this.$el.append('<div id="' + this.popupElementId + '"></div>');
        $('body').append(this.$el);
        return this;
      },
      renderHintMessages: function(newmessage) {
        var $hintEl;
        $hintEl = this.$el.find('#' + this.popupElementId);
        $hintEl.html('');
        if (newmessage) {
          this.hintMessages.boxes.push(newmessage);
        }
        this.getTpl(this.hintMessages, './novus/messaging/hintMessage.html').done((function(_this) {
          return function(out) {
            var hintMessageElement;
            hintMessageElement = $(out);
            hintMessageElement.find('.popup-message-miniicons__iconbox').last().addClass('popup-message-miniicons__iconbox--active');
            return $hintEl.html(hintMessageElement);
          };
        })(this));
      },
      gotoHintMessage: function(boxid) {
        this.$el.find('.popup-message-box').css('z-index', '9998');
        this.$el.find('.popup-message-box[data-boxid=' + boxid + ']').css('z-index', '9999');
      },
      closeHintMessage: function(boxid) {
        this.hintMessages.boxes.splice(boxid, 1);
        return this.renderHintMessages();
      },
      addMessageToFullscreenMessages: function(message) {
        var compiled, src, tmpl;
        src = '<span class="fullscreen-message__title">{caption}</span><p class="fullscreen-message__text" data-messageid="{id}">{text|s}</p>';
        compiled = window.dust.compile(src, 'msg');
        tmpl = window.dust.loadSource(compiled);
        return window.dust.render('msg', message, (function(_this) {
          return function(err, out) {
            return _this.$el.find('.fullscreen-message__container--middle').hide().prepend($(out)).fadeIn('slow');
          };
        })(this));
      },
      renderOrAddFullscreenMessage: function(message) {
        this.idsToConfirm.push(message.id);
        if (document.querySelector('.fullscreen-message')) {
          return this.addMessageToFullscreenMessages(message);
        } else {
          return this.renderFullScreenMessage(message);
        }
      },
      renderFullScreenMessage: function(message) {
        return this.getTpl(message, './novus/messaging/fullscreenMessage.html').done((function(_this) {
          return function(out) {
            var fullscreenMessageElement;
            fullscreenMessageElement = $(out);
            return _this.$el.find('#' + _this.fullScreenElementId).html(fullscreenMessageElement);
          };
        })(this));
      },
      confirmAllFullscreenMessages: function() {
        this.idsToConfirm.forEach((function(_this) {
          return function(messageid) {
            _this.confirmReading(messageid);
            return _this.idsToConfirm.splice(_this.idsToConfirm.indexOf(messageid + ''), 1);
          };
        })(this));
        this.$el.find('#' + this.fullScreenElementId).html('');
        return setTimeout((function(_this) {
          return function() {
            return localStorage[_this.fullscreenConfirmKey] = "done";
          };
        })(this), 1000);
      },
      requestCount: function() {
         this.getUserId().done(function(result) {
            this.ws.send(JSON.stringify({ type: 'COUNT', headers: {'X-Auth-Token': result['user.id']}}))
         }.bind(this));
      },
      confirmReading: function(messageId) {
        this.getUserId().done(function(result) {
            this.ws.send(JSON.stringify({ type: 'READ'
                                        , message: { id : messageId }
                                        , headers: {'X-Auth-Token': result['user.id']} }));
        }.bind(this));
      },
      /*confirmReading: function(msgId, callback) {
        var url;
        url = this.REST_URL + '/messages/' + msgId + '/read';
        return $.post(url).done((function(_this) {
          return function(response) {
            _this.requestCount();
            return _this.DEBUG && _this.log('ok', response);
          };
        })(this)).fail((function(_this) {
          return function(e) {
            return _this.log('error:', e);
          };
        })(this));
      },*/
      openWs: function() {
        if (this.ws) {
          return;
        }
        this.ws = new WebSocket(this.WS_URL);
        this.ws.onopen = (function(_this) {
          return function(e) {
            localStorage['WSaliveTicker'] = Date.now();
            _this.ticker = setInterval(function() {
              localStorage['WSaliveTicker'] = Date.now();
              return localStorage[_this.workerKey] = 'true';
            }, 1000);
            _this.getUserId().done(function(result) {
              var headers = {};
              headers['X-Auth-Token'] = result['user.id'];
              _this.ws.send(JSON.stringify({headers : headers, type : 'CONNECT'}));
              _this.DEBUG && _this.log('user id sent');
            });
          };
        })(this);
        this.ws.onmessage = (function(_this) {
          return function(e) {
            localStorage[_this.dataKey] = "";
            _this.showMessage(JSON.parse(e.data));
            localStorage[_this.dataKey] = e.data;
            _this.DEBUG && _this.log(e.data);
          };
        })(this);
        this.ws.onclose = (function(_this) {
          return function(e) {
            clearInterval(_this.ticker);
          };
        })(this);
        this.ws.onerror = (function(_this) {
          return function(e) {
            _this.DEBUG && _this.log('Messenger WebSocket error.', e);
          };
        })(this);
        window.addEventListener("beforeunload", (function(_this) {
          return function(e) {
            _this.ws.close();
          };
        })(this), false);
        window.addEventListener('unload', (function(_this) {
          return function(e) {
            _this.ws.close();
          };
        })(this));
      },
      getUserId: function() {
        var def;
        def = $.Deferred();
        $.get('context?param=user.id').done(function(data) {
          def.resolve(data);
        }).fail(function() {
          def.fail();
        });
        return def;
      },
      getTpl: function(value, src) {
        var context, def;
        context = _.extend({}, value);
        def = $.Deferred();
        src = src.match('.html') ? src : src + ".html";
        window.dust.render(src, context, function(err, out) {
          if (err) {
            return def.reject(err);
          } else {
            return def.resolve(out);
          }
        });
        return def;
      },
      socketAlive: function() {
        return (Date.now() - localStorage.getItem('WSaliveTicker')) / 1000 < 4;
      },
      runElection: function() {
        this.betMe();
        setTimeout((function(_this) {
          return function() {
            var max_tab, tabs;
            tabs = _this.getTabsForElection();
            max_tab = _.invert(tabs)[_.max(tabs)];
            if (max_tab === _this.myTabId) {
              _this.openWs();
              localStorage[_this.workerKey] = 'true';
            }
            _this.removeElection();
          };
        })(this), 500);
      },
      runChecker: function() {
        return this.checker = setInterval((function(_this) {
          return function() {
            if (!_this.socketAlive() && localStorage[_this.election_key] !== 'true') {
              _this.DEBUG && _this.log('Сокет просрочился, начинаем выборы!');
              localStorage[_this.election_key] = "true";
              _this.runElection();
            }
          };
        })(this), 2000);
      },
      betMe: function() {
        this.myTabId = 'tab-' + this.guid();
        localStorage[this.myTabId] = Math.random();
        return this.DEBUG && this.log(this.myTabId, localStorage[this.myTabId]);
      },
      getTabsForElection: function() {
        var i, tabs;
        tabs = {};
        i = 0;
        while (i < localStorage.length) {
          if (localStorage.key(i).substring(0, 3) === 'tab') {
            tabs[localStorage.key(i)] = localStorage.getItem(localStorage.key(i));
          }
          i++;
        }
        return tabs;
      },
      removeElection: function() {
        var key, results;
        localStorage[this.election_key] = 'false';
        results = [];
        for (key in localStorage) {
          if (key.substring(0, 3) === 'tab') {
            results.push(localStorage.removeItem(key));
          } else {
            results.push(void 0);
          }
        }
        return results;
      },
      log: function() {
        [].slice.call(arguments).forEach(function(el) {
          if (typeof el === 'string') {
            return console.error('%c' + el, 'font-size: 20px;');
          } else {
            return console.error(el);
          }
        });
      },
      guid: function() {
        return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
      }
    });
  });

}).call(this);

//# sourceMappingURL=notification.js.map
