spring.datasource:
  url: jdbc:postgresql://localhost/messaging
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver

spring.jooq.sql-dialect: Postgres

spring.jackson.serialization.write_dates_as_timestamps: false

security.user:
  name: admin
  password: admin

spring.kafka:
  consumer.group-id: novus-messaging
  bootstrap-servers: localhost:9092

spring.activemq:
  broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
#  broker-url: tcp://localhost:61616

novus.messaging:
  timeout: 60
  topic:
    notice: novus-messaging-notify
    email: novus-messaging-email
  durable: true
  auth-header-name: X-Auth-Token
  keycloak.modulus: rnOzE3m3ohRrASPvNUT2sDEaOf-E1qlttRbr4inxUGe2e_SdS-IGqjOzME2H-IByHPEqH5ptZ1GjhHaMo81conYBoA6Dgwz8wo4oARSKRgFXOgqybcBQu_ruUGrbsRD7UvEDNYin84gUkeHSQUJJjBb4f71yUjcWNpD-sC5vpSaPJNgVP1q5kKTjGd6eRmGF2bD0MQHPh_leGWKCxbcOqSxHmQiLV7qGqouJ6YuHCQG3plzuUGmk2fnWzCZ9l1qEoIh-JE0Z3kquroqG9jVzQd5u9Ct6JX2OeXjn4bXzSND_Um6Zztw41XJs1QFPXHA2HVoCeJ1CCm1UtVTUCB0uHw
  keycloak.exponent: AQAB
  keycloak.resourceId: lkb-app
  app_prefix: /app
  end_point: /ws
  public_dest_prefix: /topic
  private_dest_prefix: /exchange
  check_token_expired: true

management:
  context-path: /actuator
  security:
    roles: SUPERUSER

#email sender
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: no.reply.notify.domrf
spring.mail.password: 3hTkZft4wGmk6L8h
spring.mail.properties.mail.smtps.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.debug: false


cxf.path: /api
cxf.jaxrs.component-scan: true
cxf.servlet.init.service-list-path: /info
jaxrs.swagger.enabled: true
jaxrs.swagger.title: REST for Messaging
jaxrs.swagger.version: 1.0
jaxrs.swagger.resource-package: ru.inovus.messaging.api.rest

sec:
  admin:
    rest:
      url: http://docker.one:31888/api
spring.http.encoding.forceResponse: true
spring.http.encoding.force: true

keycloak.redirect-url: http://localhost:8081
keycloak.server-url: https://keycloak.i-novus.ru/auth
keycloak.realm: security-admin

security:
  oauth2:
    auth-server-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect
    resource:
      id: messaging-service
      token-info-uri: ${security.oauth2.auth-server-uri}/token/introspect
      user-info-uri: ${security.oauth2.auth-server-uri}/userinfo
      jwt.key-value: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi54+TgAUWz3rUrAqdjBcmw6lueJdDcDh5ymU3uuNJsBOTz4mI3lFle505/xta6mpaMZynoS9Nbs6HJswWScCNilc97GFpFpn1KMYV0Ct8Mk0R2gEBk3ky+ASjhMXdd0UIhFywHivU0eaVQVXLfFFg68b/MK4NyJTR33pgUy7VZTtup+h8UFWzVuKu1tfrI6rVe6o2biKM+z258uWXxbEI08DyBTyvAL+GKb0HY1G59BQ/6rziYCVDSO3EQgb+rL4ZNmlVb13W0ePfyWUKnBPcmk9TRejaYmYSZiwQjDgx9+1yBCEeDPPt/LyVAac2Bd5Vq2VVJfz7bUf2TTwT9hBdQIDAQAB
        -----END PUBLIC KEY-----
#    client:
#      client-id: messaging-service
#      client-secret: 0172295d-3343-4068-9d13-b6f9df3157b3
#      scope: senduser,sendgroup,sendall
#      access-token-uri: ${security.oauth2.auth-server-uri}/token
#      grant-type: client_credentials

server:
  port: 8081