server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost/messaging
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: default

spring.jooq.sql-dialect: Postgres

spring.jackson.serialization.write_dates_as_timestamps: false

messaging:
  mapping-file-location: classpath:userRoleProviderFieldMapping.xml
  user-role-provider: configurable
  user-provider-url: http://localhost:9999/api/users
  role-provider-url: http://localhost:9999/api/role

security.user:
  name: admin
  password: admin

spring.kafka:
  consumer.group-id: novus-messaging
  bootstrap-servers: localhost:9092

spring.activemq:
  broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
#  broker-url: tcp://localhost:61616

novus.messaging:
  timeout: 60
  topic:
    notice: novus-messaging-notify
    email: novus-messaging-email

  redelivery-policy:                              # настройки повторной отправки сообщений (только для очередей activeMQ) см. https://activemq.apache.org/redelivery-policy
    novus-messaging-email:
      initial-redelivery-delay: 60000              # интервал между первой отправкой сообщения и первой повторной отправкой сообщения, мс. (только для очередей activeMQ)
      redelivery-delay: 60000                      # интервал между последующими повторными отправками сообщения, мс. (только для очередей activeMQ)
      maximum-redeliveries: 7                     # число повторных отправок сообщения, не считая первую отправку сообщения (только для очередей activeMQ)
      use-exponential-back-off: false             # изменять ли интервал повторной отправки сообщения (только для очередей activeMQ)
      back-off-multiplier: 2                      # коэффициент изменения интервала повторной отправки сообщения (только для очередей activeMQ)

  durable: true
  auth-header-name: X-Auth-Token
  keycloak.modulus: rnOzE3m3ohRrASPvNUT2sDEaOf-E1qlttRbr4inxUGe2e_SdS-IGqjOzME2H-IByHPEqH5ptZ1GjhHaMo81conYBoA6Dgwz8wo4oARSKRgFXOgqybcBQu_ruUGrbsRD7UvEDNYin84gUkeHSQUJJjBb4f71yUjcWNpD-sC5vpSaPJNgVP1q5kKTjGd6eRmGF2bD0MQHPh_leGWKCxbcOqSxHmQiLV7qGqouJ6YuHCQG3plzuUGmk2fnWzCZ9l1qEoIh-JE0Z3kquroqG9jVzQd5u9Ct6JX2OeXjn4bXzSND_Um6Zztw41XJs1QFPXHA2HVoCeJ1CCm1UtVTUCB0uHw
  keycloak.exponent: AQAB
  keycloak.resourceId: lkb-app
  app_prefix: /app
  end_point: /ws
  public_dest_prefix: /topic
  private_dest_prefix: /exchange
  check_token_expired: true
  username.alias: preferred_username

#email sender
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: no.reply.notify.domrf
spring.mail.password: 3hTkZft4wGmk6L8h
spring.mail.properties.mail.smtps.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.debug: false


cxf.path: /api
cxf.jaxrs.component-scan: true
cxf.servlet.init.service-list-path: /info
jaxrs.swagger.enabled: true
jaxrs.swagger.title: REST for Messaging
jaxrs.swagger.version: 1.0
jaxrs.swagger.resource-package: ru.inovus.messaging.api.rest

sec:
  admin:
    rest:
      url: http://localhost:9999/api
      enable: true

spring.http.encoding.forceResponse: true
spring.http.encoding.force: true

keycloak.redirect-url: http://localhost:${server.port}
keycloak.server-url: https://keycloak.i-novus.ru/auth
keycloak.realm: security-admin