/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.inovus.messaging.impl.jooq.tables.*;
import ru.inovus.messaging.impl.jooq.tables.records.*;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>messaging</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AttachmentRecord> ATTACHMENT_PKEY = UniqueKeys0.ATTACHMENT_PKEY;
    public static final UniqueKey<ChannelRecord> CHANNEL_PKEY = UniqueKeys0.CHANNEL_PKEY;
    public static final UniqueKey<MessageRecord> MESSAGE_PKEY = UniqueKeys0.MESSAGE_PKEY;
    public static final UniqueKey<MessageRecipientRecord> MESSAGE_RECIPIENT_PKEY = UniqueKeys0.MESSAGE_RECIPIENT_PKEY;
    public static final UniqueKey<MessageTemplateRecord> MESSAGE_TEMPLATE_PKEY = UniqueKeys0.MESSAGE_TEMPLATE_PKEY;
    public static final UniqueKey<MessageTemplateRecord> MESSAGE_TEMPLATE_CODE_KEY = UniqueKeys0.MESSAGE_TEMPLATE_CODE_KEY;
    public static final UniqueKey<TenantRecord> TENANT_PKEY = UniqueKeys0.TENANT_PKEY;
    public static final UniqueKey<RecipientGroupRecord> RECIPIENT_GROUP_PKEY = UniqueKeys0.RECIPIENT_GROUP_PKEY;
    public static final UniqueKey<RecipientGroupTemplateRecord> RECIPIENT_GROUP_TEMPLATE_PKEY = UniqueKeys0.RECIPIENT_GROUP_TEMPLATE_PKEY;
    public static final UniqueKey<RecipientGroupUserRecord> RECIPIENT_GROUP_USER_PKEY = UniqueKeys0.RECIPIENT_GROUP_USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AttachmentRecord, MessageRecord> ATTACHMENT__ATTACHMENT_MESSAGE_ID_FK = ForeignKeys0.ATTACHMENT__ATTACHMENT_MESSAGE_ID_FK;
    public static final ForeignKey<MessageRecord, TenantRecord> MESSAGE__MESSAGE_TENANT_CODE_FKEY = ForeignKeys0.MESSAGE__MESSAGE_TENANT_CODE_FKEY;
    public static final ForeignKey<MessageRecord, ChannelRecord> MESSAGE__MESSAGE_CHANNEL_CODE_CHANNEL_CODE_FK = ForeignKeys0.MESSAGE__MESSAGE_CHANNEL_CODE_CHANNEL_CODE_FK;
    public static final ForeignKey<MessageRecipientRecord, MessageRecord> MESSAGE_RECIPIENT__MESSAGE_RECIPIENT_MESSAGE_ID_FKEY = ForeignKeys0.MESSAGE_RECIPIENT__MESSAGE_RECIPIENT_MESSAGE_ID_FKEY;
    public static final ForeignKey<MessageTemplateRecord, ChannelRecord> MESSAGE_TEMPLATE__MESSAGE_TEMPLATE_CHANNEL_CODE_CHANNEL_CODE_FK = ForeignKeys0.MESSAGE_TEMPLATE__MESSAGE_TEMPLATE_CHANNEL_CODE_CHANNEL_CODE_FK;
    public static final ForeignKey<MessageTemplateRecord, TenantRecord> MESSAGE_TEMPLATE__MESSAGE_TEMPLATE_TENANT_CODE_FKEY = ForeignKeys0.MESSAGE_TEMPLATE__MESSAGE_TEMPLATE_TENANT_CODE_FKEY;
    public static final ForeignKey<RecipientGroupRecord, TenantRecord> RECIPIENT_GROUP_TENANT_CODE_FKEY = ForeignKeys0.RECIPIENT_GROUP_TENANT_CODE_FKEY;
    public static final ForeignKey<RecipientGroupUserRecord, RecipientGroupRecord> RECIPIENT_GROUP_USER_RECIPIENT_GROUP_ID_FKEY = ForeignKeys0.RECIPIENT_GROUP_USER_RECIPIENT_GROUP_ID_FKEY;
    public static final ForeignKey<RecipientGroupTemplateRecord, RecipientGroupRecord> RECIPIENT_GROUP_TEMPLATE_RECIPIENT_GROUP_ID_FKEY = ForeignKeys0.RECIPIENT_GROUP_TEMPLATE_RECIPIENT_GROUP_ID_FKEY;
    public static final ForeignKey<RecipientGroupTemplateRecord, MessageTemplateRecord> RECIPIENT_GROUP_TEMPLATE_MESSAGE_TEMPLATE_CODE_FKEY = ForeignKeys0.RECIPIENT_GROUP_TEMPLATE_MESSAGE_TEMPLATE_CODE_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AttachmentRecord> ATTACHMENT_PKEY = Internal.createUniqueKey(Attachment.ATTACHMENT, "attachment_pkey", new TableField[] { Attachment.ATTACHMENT.ID }, true);
        public static final UniqueKey<ChannelRecord> CHANNEL_PKEY = Internal.createUniqueKey(Channel.CHANNEL, "channel_pkey", new TableField[] { Channel.CHANNEL.CODE }, true);
        public static final UniqueKey<MessageRecord> MESSAGE_PKEY = Internal.createUniqueKey(Message.MESSAGE, "message_pkey", new TableField[] { Message.MESSAGE.ID }, true);
        public static final UniqueKey<MessageRecipientRecord> MESSAGE_RECIPIENT_PKEY = Internal.createUniqueKey(MessageRecipient.MESSAGE_RECIPIENT, "message_recipient_pkey", new TableField[] { MessageRecipient.MESSAGE_RECIPIENT.ID }, true);
        public static final UniqueKey<MessageTemplateRecord> MESSAGE_TEMPLATE_PKEY = Internal.createUniqueKey(MessageTemplate.MESSAGE_TEMPLATE, "message_template_pkey", new TableField[] { MessageTemplate.MESSAGE_TEMPLATE.ID }, true);
        public static final UniqueKey<MessageTemplateRecord> MESSAGE_TEMPLATE_CODE_KEY = Internal.createUniqueKey(MessageTemplate.MESSAGE_TEMPLATE, "message_template_code_key", new TableField[] { MessageTemplate.MESSAGE_TEMPLATE.CODE }, true);
        public static final UniqueKey<TenantRecord> TENANT_PKEY = Internal.createUniqueKey(Tenant.TENANT, "tenant_pkey", new TableField[] { Tenant.TENANT.CODE }, true);
        public static final UniqueKey<RecipientGroupRecord> RECIPIENT_GROUP_PKEY = Internal.createUniqueKey(Tables.RECIPIENT_GROUP, "recipient_group_pkey", new TableField[] { Tables.RECIPIENT_GROUP.ID }, true);
        public static final UniqueKey<RecipientGroupUserRecord> RECIPIENT_GROUP_USER_PKEY = Internal.createUniqueKey(Tables.RECIPIENT_GROUP_USER, "recipient_group_user_pkey", new TableField[] { Tables.RECIPIENT_GROUP_USER.ID }, true);
        public static final UniqueKey<RecipientGroupTemplateRecord> RECIPIENT_GROUP_TEMPLATE_PKEY = Internal.createUniqueKey(Tables.RECIPIENT_GROUP_TEMPLATE, "recipient_group_template_pkey", new TableField[] { Tables.RECIPIENT_GROUP_TEMPLATE.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AttachmentRecord, MessageRecord> ATTACHMENT__ATTACHMENT_MESSAGE_ID_FK = Internal.createForeignKey(Keys.MESSAGE_PKEY, Attachment.ATTACHMENT, "attachment_message_id_fk", new TableField[] { Attachment.ATTACHMENT.MESSAGE_ID }, true);
        public static final ForeignKey<MessageRecord, TenantRecord> MESSAGE__MESSAGE_TENANT_CODE_FKEY = Internal.createForeignKey(Keys.TENANT_PKEY, Message.MESSAGE, "message_tenant_code_fkey", new TableField[] { Message.MESSAGE.TENANT_CODE }, true);
        public static final ForeignKey<MessageRecord, ChannelRecord> MESSAGE__MESSAGE_CHANNEL_CODE_CHANNEL_CODE_FK = Internal.createForeignKey(Keys.CHANNEL_PKEY, Message.MESSAGE, "message_channel_code_channel_code_fk", new TableField[] { Message.MESSAGE.CHANNEL_CODE }, true);
        public static final ForeignKey<MessageRecipientRecord, MessageRecord> MESSAGE_RECIPIENT__MESSAGE_RECIPIENT_MESSAGE_ID_FKEY = Internal.createForeignKey(Keys.MESSAGE_PKEY, MessageRecipient.MESSAGE_RECIPIENT, "message_recipient_message_id_fkey", new TableField[] { MessageRecipient.MESSAGE_RECIPIENT.MESSAGE_ID }, true);
        public static final ForeignKey<MessageTemplateRecord, ChannelRecord> MESSAGE_TEMPLATE__MESSAGE_TEMPLATE_CHANNEL_CODE_CHANNEL_CODE_FK = Internal.createForeignKey(Keys.CHANNEL_PKEY, MessageTemplate.MESSAGE_TEMPLATE, "message_template_channel_code_channel_code_fk", new TableField[] { MessageTemplate.MESSAGE_TEMPLATE.CHANNEL_CODE }, true);
        public static final ForeignKey<MessageTemplateRecord, TenantRecord> MESSAGE_TEMPLATE__MESSAGE_TEMPLATE_TENANT_CODE_FKEY = Internal.createForeignKey(Keys.TENANT_PKEY, MessageTemplate.MESSAGE_TEMPLATE, "message_template_tenant_code_fkey", new TableField[] { MessageTemplate.MESSAGE_TEMPLATE.TENANT_CODE }, true);
        public static final ForeignKey<RecipientGroupRecord, TenantRecord> RECIPIENT_GROUP_TENANT_CODE_FKEY = Internal.createForeignKey(Keys.TENANT_PKEY, Tables.RECIPIENT_GROUP, "recipient_group_tenant_code_fkey", new TableField[] { Tables.RECIPIENT_GROUP.TENANT_CODE }, true);
        public static final ForeignKey<RecipientGroupUserRecord, RecipientGroupRecord> RECIPIENT_GROUP_USER_RECIPIENT_GROUP_ID_FKEY = Internal.createForeignKey(Keys.RECIPIENT_GROUP_USER_PKEY, Tables.RECIPIENT_GROUP_USER, "recipient_group_user_recipient_group_id_fkey", new TableField[] { Tables.RECIPIENT_GROUP_USER.RECIPIENT_GROUP_ID }, true);
        public static final ForeignKey<RecipientGroupTemplateRecord, RecipientGroupRecord> RECIPIENT_GROUP_TEMPLATE_RECIPIENT_GROUP_ID_FKEY = Internal.createForeignKey(Keys.RECIPIENT_GROUP_TEMPLATE_PKEY, Tables.RECIPIENT_GROUP_TEMPLATE, "recipient_group_template_recipient_group_id_fkey", new TableField[] { Tables.RECIPIENT_GROUP_TEMPLATE.RECIPIENT_GROUP_ID }, true);
        public static final ForeignKey<RecipientGroupTemplateRecord, MessageTemplateRecord> RECIPIENT_GROUP_TEMPLATE_MESSAGE_TEMPLATE_CODE_FKEY = Internal.createForeignKey(Keys.MESSAGE_TEMPLATE_CODE_KEY, Tables.RECIPIENT_GROUP_TEMPLATE, "recipient_group_template_message_template_code_fkey", new TableField[] { Tables.RECIPIENT_GROUP_TEMPLATE.MESSAGE_TEMPLATE_CODE }, true);
        public static final ForeignKey<RecipientGroupTemplateRecord, MessageTemplateRecord> RECIPIENT_GROUP_TEMPLATE_MESSAGE_TEMPLATE_ID_FKEY = Internal.createForeignKey(Keys.MESSAGE_TEMPLATE_PKEY, Tables.RECIPIENT_GROUP_TEMPLATE, "recipient_group_template_message_template_id_fkey", new TableField[] { Tables.RECIPIENT_GROUP_TEMPLATE.MESSAGE_TEMPLATE_ID }, true);
    }
}
