/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.inovus.messaging.impl.jooq.tables.Attachment;
import ru.inovus.messaging.impl.jooq.tables.Channel;
import ru.inovus.messaging.impl.jooq.tables.Message;
import ru.inovus.messaging.impl.jooq.tables.MessageRecipient;
import ru.inovus.messaging.impl.jooq.tables.MessageTemplate;
import ru.inovus.messaging.impl.jooq.tables.RecipientGroup;
import ru.inovus.messaging.impl.jooq.tables.RecipientGroupTemplate;
import ru.inovus.messaging.impl.jooq.tables.RecipientGroupUser;
import ru.inovus.messaging.impl.jooq.tables.Tenant;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messaging extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>messaging</code>
     */
    public static final Messaging MESSAGING = new Messaging();

    /**
     * Вложения
     */
    public final Attachment ATTACHMENT = Attachment.ATTACHMENT;

    /**
     * Каналы отправки уведомлений
     */
    public final Channel CHANNEL = Channel.CHANNEL;

    /**
     * Уведомления
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * Получатель уведомления
     */
    public final MessageRecipient MESSAGE_RECIPIENT = MessageRecipient.MESSAGE_RECIPIENT;

    /**
     * Шаблоны уведомлений
     */
    public final MessageTemplate MESSAGE_TEMPLATE = MessageTemplate.MESSAGE_TEMPLATE;

    /**
     * Группы получателей
     */
    public final RecipientGroup RECIPIENT_GROUP = RecipientGroup.RECIPIENT_GROUP;

    /**
     * Связь шаблонов с группой
     */
    public final RecipientGroupTemplate RECIPIENT_GROUP_TEMPLATE = RecipientGroupTemplate.RECIPIENT_GROUP_TEMPLATE;

    /**
     * Связь получателей с группой
     */
    public final RecipientGroupUser RECIPIENT_GROUP_USER = RecipientGroupUser.RECIPIENT_GROUP_USER;

    /**
     * Тенанты
     */
    public final Tenant TENANT = Tenant.TENANT;

    /**
     * No further instances allowed
     */
    private Messaging() {
        super("messaging", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.MESSAGE_ID_SEQ,
            Sequences.MESSAGE_RECIPIENT_ID_SEQ,
            Sequences.MESSAGE_TEMPLATE_ID_SEQ,
            Sequences.RECIPIENT_GROUP_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Attachment.ATTACHMENT,
            Channel.CHANNEL,
            Message.MESSAGE,
            MessageRecipient.MESSAGE_RECIPIENT,
            MessageTemplate.MESSAGE_TEMPLATE,
            RecipientGroup.RECIPIENT_GROUP,
            RecipientGroupTemplate.RECIPIENT_GROUP_TEMPLATE,
            RecipientGroupUser.RECIPIENT_GROUP_USER,
            Tenant.TENANT
        );
    }
}
