/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.inovus.messaging.impl.jooq.tables.Component;
import ru.inovus.messaging.impl.jooq.tables.Message;
import ru.inovus.messaging.impl.jooq.tables.MessageSetting;
import ru.inovus.messaging.impl.jooq.tables.Recipient;
import ru.inovus.messaging.impl.jooq.tables.UserSetting;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1285580624;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Компоненты системы
     */
    public final Component COMPONENT = ru.inovus.messaging.impl.jooq.tables.Component.COMPONENT;

    /**
     * Сообщения
     */
    public final Message MESSAGE = ru.inovus.messaging.impl.jooq.tables.Message.MESSAGE;

    /**
     * Шаблоны уведомлений (общесистемные настройки)
     */
    public final MessageSetting MESSAGE_SETTING = ru.inovus.messaging.impl.jooq.tables.MessageSetting.MESSAGE_SETTING;

    /**
     * Получатели сообщения
     */
    public final Recipient RECIPIENT = ru.inovus.messaging.impl.jooq.tables.Recipient.RECIPIENT;

    /**
     * Пользовательские настройки уведомлений
     */
    public final UserSetting USER_SETTING = ru.inovus.messaging.impl.jooq.tables.UserSetting.USER_SETTING;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.MESSAGE_ID_SEQ,
            Sequences.MESSAGE_SETTING_ID_SEQ,
            Sequences.RECIPIENT_ID_SEQ,
            Sequences.USER_SETTING_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Component.COMPONENT,
            Message.MESSAGE,
            MessageSetting.MESSAGE_SETTING,
            Recipient.RECIPIENT,
            UserSetting.USER_SETTING);
    }
}
