/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import ru.inovus.messaging.impl.jooq.tables.*;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -82604470;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Канал отправки
     */
    public final Channel CHANNEL = Channel.CHANNEL;

    /**
     * Компоненты системы
     */
    public final Component COMPONENT = Component.COMPONENT;

    /**
     * Сообщения
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * Шаблоны уведомлений (общесистемные настройки)
     */
    public final MessageSetting MESSAGE_SETTING = MessageSetting.MESSAGE_SETTING;

    /**
     * Получатели сообщения
     */
    public final Recipient RECIPIENT = Recipient.RECIPIENT;

    /**
     * Пользовательские настройки уведомлений
     */
    public final UserSetting USER_SETTING = UserSetting.USER_SETTING;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
                Sequences.MESSAGE_ID_SEQ,
                Sequences.MESSAGE_SETTING_ID_SEQ,
                Sequences.RECIPIENT_ID_SEQ,
                Sequences.USER_SETTING_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Channel.CHANNEL,
                Component.COMPONENT,
                Message.MESSAGE,
                MessageSetting.MESSAGE_SETTING,
                Recipient.RECIPIENT,
                UserSetting.USER_SETTING);
    }
}
