/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in messaging.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>messaging.message_id_seq</code>
     */
    public static final Sequence<Long> MESSAGE_ID_SEQ = Internal.createSequence("message_id_seq", Messaging.MESSAGING, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>messaging.message_recipient_id_seq</code>
     */
    public static final Sequence<Long> MESSAGE_RECIPIENT_ID_SEQ = Internal.createSequence("message_recipient_id_seq", Messaging.MESSAGING, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>messaging.message_template_id_seq</code>
     */
    public static final Sequence<Long> MESSAGE_TEMPLATE_ID_SEQ = Internal.createSequence("message_template_id_seq", Messaging.MESSAGING, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>messaging.recipient_group_id_seq</code>
     */
    public static final Sequence<Long> RECIPIENT_GROUP_ID_SEQ = Internal.createSequence("recipient_group_id_seq", Messaging.MESSAGING, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
