/*
 * This file is generated by jOOQ.
 */
package ru.inovus.messaging.impl.jooq;


import ru.inovus.messaging.impl.jooq.tables.*;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * Компоненты системы
     */
    public static final Component COMPONENT = Component.COMPONENT;

    /**
     * Сообщения
     */
    public static final Message MESSAGE = Message.MESSAGE;

    /**
     * Шаблоны уведомлений (общесистемные настройки)
     */
    public static final MessageSetting MESSAGE_SETTING = MessageSetting.MESSAGE_SETTING;

    /**
     * Получатели сообщения
     */
    public static final Recipient RECIPIENT = Recipient.RECIPIENT;

    /**
     * Пользовательские настройки уведомлений
     */
    public static final UserSetting USER_SETTING = UserSetting.USER_SETTING;
}
