{{- $db := index .Values "genericServices" "messaging-db" }}
{{- $usesPvc := false }}
{{- range $db.volumes }}
  {{- if .persistentVolumeClaim }}
    {{- $usesPvc = true }}
  {{- end }}
{{- end }}
{{- if $usesPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: messaging-db-data
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ coalesce $db.storageClassName "retain" }}
{{- end }}
